@echo off
REM ─────────────────────────────────────────────────────────────
REM Pacific Observatory CLI launcher
REM Invokes the venv's python.exe on run.py directly, bypassing
REM the pip-generated po.exe console_script launcher.
REM
REM Why: po.exe is an unsigned launcher stub generated by pip.
REM Some corporate AppLocker policies allow PSF-signed python.exe
REM but block unsigned .exe files in user-writable directories.
REM Calling python.exe on run.py (a plain .py file) sidesteps
REM the publisher rule entirely.
REM ─────────────────────────────────────────────────────────────

set "VENV_PY=%~dp0.venv\Scripts\python.exe"
set "RUN_PY=%~dp0run.py"

if not exist "%VENV_PY%" (
    echo [ERROR] Could not find %VENV_PY%
    echo         Run setup.bat first to create the environment.
    exit /b 1
)

if not exist "%RUN_PY%" (
    echo [ERROR] Could not find %RUN_PY%
    echo         This file should ship with the repo.
    exit /b 1
)

"%VENV_PY%" "%RUN_PY%" %*
exit /b %errorlevel%
