
import pandas as pd

# Load the datasets
try:
    mis_prods = pd.read_csv('mis_prods2.csv')
    coicop = pd.read_csv('coicop_categories_no_services.csv')
except FileNotFoundError as e:
    print(f"Error loading files: {e}")
    exit()


# Create a mapping from category description to code and title
coicop_map = coicop.set_index('title')['code'].to_dict()
coicop_title_map = coicop.set_index('code')['title'].to_dict()

# Invert the map for easier lookup
title_to_code = {v: k for k, v in coicop_map.items()}

# Simplified mapping from product category strings to COICOP titles
# This is a best-effort mapping based on keywords
category_mapping = {
    'pantry confectionery': 'Other sugar confectionery and desserts n.e.c. (ND)',
    'baby care': 'Travel goods, baby articles and other personal effects n.e.c. (SD)',
    'sanitary toilet paper': 'Other appliances, articles and products for personal care (ND)',
    'rice': 'Cereals (ND)',
    'cake mix essentials': 'Other milled cereal and grain products (ND)',
    'baking products': 'Other milled cereal and grain products (ND)',
    'flour sharp': 'Flour of cereals (ND)',
    'dried legumes': 'Pulses (ND)',
    'snacks savouries': 'Other milled cereal and grain products (ND)',
    'spices': 'Spices, culinary herbs and seeds (ND)',
    'desserts': 'Other sugar confectionery and desserts n.e.c. (ND)',
    'confectionery': 'Other sugar confectionery and desserts n.e.c. (ND)',
    'oil': 'Vegetable oils (ND)',
    'chocolates': 'Chocolate, cocoa and cocoa-based food products (ND)',
    'biscuit': 'Bread and bakery products (ND)',
    'sugar': 'Cane sugar and beet sugar (ND)',
    'essences colours syrups': 'Other sugars and sugar substitutes (ND)',
    'infant food': 'Baby food (ND)',
    'edible oil': 'Vegetable oils (ND)',
    'milk': 'Other milk and cream (ND)',
    'dried fruits': 'Fruits, dried and dehydrated (ND)',
    'canned vegetables': 'Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations (ND)',
    'sauce': 'Salt, condiments and sauces (ND)',
    'frozen sausages': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'frozen poultry': 'Meat, fresh, chilled or frozen (ND)',
    'frozen icecream deserts': 'Ice, ice cream and sorbets (ND)',
    'personal care': 'Other appliances, articles and products for personal care (ND)',
    'hair care': 'Other appliances, articles and products for personal care (ND)',
    'electrical': 'Miscellaneous accessories (SD)',
    'disposable products': 'Other non-durable household goods (ND)',
    'dishwashing': 'Household cleaning and maintenance products (ND)',
    'home kitchen care': 'Household cleaning and maintenance products (ND)',
    'lubes': 'Lubricants (ND)',
    'alcoholic beverage beer': 'Beer (ND)',
    'alcoholic beverage local rtd': 'Other alcoholic beverages (ND)',
    'adult diaper': 'Assistive products for mobility and daily living (D)',
    'pet accessories': 'Products for pets and other household animals (ND)',
    'pet care': 'Products for pets and other household animals (ND)',
    'pharmaceuticals': 'Medicines, vaccines and other pharmaceutical preparations (ND)',
    'alcoholic beverage imported wines': 'Wine from grapes (ND)',
    'frozen frozen chicken': 'Meat, fresh, chilled or frozen (ND)',
    'oral care': 'Other appliances, articles and products for personal care (ND)',
    'fabric care': 'Household cleaning and maintenance products (ND)',
    'repellants': 'Other non-durable household goods (ND)',
    'cooking requirements': 'Liquefied hydrocarbons (ND)',
    'beverage beverage hot coffee': 'Coffee and coffee substitutes (ND)',
    'alcoholic beverage imported spirits': 'Spirits and liquors (ND)',
    'beverage beverage cold': 'Soft drinks (ND)',
    'beverage beverage hot chocolate': 'Cocoa drinks (ND)',
    'beverage beverage hot tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'school office covers tapes': 'Stationery and drawing materials (ND)',
    'beverage water': 'Water (ND)',
    'dairy spreads': 'Margarine and similar preparations (ND)',
    'dairy cheese': 'Cheese (ND)',
    'dairy local imported cultured products': 'Yoghurt and similar products (ND)',
    'school office writing postage materials': 'Stationery and drawing materials (ND)',
    'frozen frozen vegetables': 'Vegetables, tubers, plantains and cooking bananas, frozen (ND)',
    'frozen lamb': 'Meat, fresh, chilled or frozen (ND)',
    'frozen chicken': 'Meat, fresh, chilled or frozen (ND)',
    'fruits vegetables imported fruits': 'Other fruits, fresh (ND)',
    'lighters': 'Travel goods, baby articles and other personal effects n.e.c. (SD)',
    'canned fish': 'Fish preparations (ND)',
    'fruits vegetables imported vegetables': 'Other vegetables, fresh or chilled (ND)',
    'canned fruits': 'Fruits and nuts, ground, and in other preparations (ND)',
    'breakfast': 'Breakfast cereals (ND)',
    'noodles': 'Macaroni, noodles, couscous and similar pasta products (ND)',
    'soups': 'Ready-made food (ND)',
    'pasta': 'Macaroni, noodles, couscous and similar pasta products (ND)',
    'vinegar': 'Salt, condiments and sauces (ND)',
    'salad dressings': 'Salt, condiments and sauces (ND)',
    'seasoning': 'Salt, condiments and sauces (ND)',
    'canned seafood': 'Other seafood preparations (ND)',
    'spread': 'Margarine and similar preparations (ND)',
    'baked bean spaghetti': 'Ready-made food (ND)',
    'canned meat': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'juices water energy drink': 'Other non-alcoholic beverages (ND)',
    'breakfast needs': 'Breakfast cereals (ND)',
    'lentils spices masala mix pickles': 'Spices, culinary herbs and seeds (ND)',
    'drinks milk tea coffee food beverage': 'Water (ND)', # Generic fallback
    'paper foils disposables': 'Other non-durable household goods (ND)',
    'spreads sauces dressings': 'Salt, condiments and sauces (ND)',
    'canned vegetables meat': 'Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations (ND)',
    'beef meat': 'Meat, fresh, chilled or frozen (ND)',
    'bakery': 'Bread and bakery products (ND)',
    'meat poultry': 'Meat, fresh, chilled or frozen (ND)',
    'lamb meat': 'Meat, fresh, chilled or frozen (ND)',
    'meat poultry ready eat': 'Ready-made food (ND)',
    'meat pork': 'Meat, fresh, chilled or frozen (ND)',
    'bakery cakes': 'Bread and bakery products (ND)',
    'ham bacon meat pork smallgoods': 'Meat, dried, salted, in brine or smoked (ND)',
    'ham bacon smallgoods': 'Meat, dried, salted, in brine or smoked (ND)',
    'sausages smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'pork sausages smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'beef sausages smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'pork': 'Meat, fresh, chilled or frozen (ND)',
    'sausages': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'ready eat sausages smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'beef smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'ready eat smallgoods': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'lamb': 'Meat, fresh, chilled or frozen (ND)',
    'poultry': 'Meat, fresh, chilled or frozen (ND)',
    'ready eat seafood': 'Other seafood preparations (ND)',
    'beverage milk macro organic unsweetened oat milk': 'Non-animal milk (ND)',
    'beverage sparkling water bel normande sparkling white grape': 'Water (ND)',
    'beverage drink mix powder vitafresh sweet navel orange': 'Other non-alcoholic beverages (ND)',
    'beverage coffee nescafe latte': 'Coffee and coffee substitutes (ND)',
    'beverage soda woolworths passion fruit flavored ltr': 'Soft drinks (ND)',
    'beverage juice nectar ribena blackcurrant fruit drink': 'Fruit and vegetable juices (ND)',
    'beverage milk anchor calciyum milk banana ml': 'Milk-based dessert and beverages (ND)',
    'beverage energy drink rockstar tropical guava': 'Other non-alcoholic beverages (ND)',
    'beverage energy drink powerade mountain berryblast': 'Other non-alcoholic beverages (ND)',
    'beverage milk pocasville horchata original': 'Non-animal milk (ND)',
    'beverage sparkling water liquid death sparkling water': 'Water (ND)',
    'beverage drink mix powder nestle rich milk chocolate flavor': 'Cocoa drinks (ND)',
    'beverage coffee nescafe mocha': 'Coffee and coffee substitutes (ND)',
    'beverage soda squirt grape fruit soda': 'Soft drinks (ND)',
    'beverage juice nectar yogo aloe vera peach': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar yogo aloe vera melon': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar jumex strawberry nectar ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar jumex pineapple nectar ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar jumex mango nectar ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar mccoy cranberry juice ltr': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar mccoy tomato juice ltr': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar mccoy dark grape ltr': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar mccoy orange juice ltr': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar mccoy pineapple juice ltr': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar juice apple': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar langers mongo mango': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar yogo aloe vera strawberry': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar yogo aloe vera mango': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar california gold prune juice ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar fresh apple sum ahh fruits': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar fresh harvest red apple': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar kern guava nectar': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar keri juice co pulpy pineapple fruit': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar keri juice co apple juice': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar gabriela chia seed strawberry fl oz ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar gabriela chia seed mango ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar well aloe vera drink original': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar well aloe vera drink original ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar juice orange apple apple base': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar juice tropical apple base': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar arizona natural lemonade ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar arizona natural fruit punch ml': 'Fruit and vegetable juices (ND)',
    'beverage juice nectar arizona diet green tea ginseng ml': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage juice nectar hi fru bu tropical fruit flavoured drink': 'Fruit and vegetable juices (ND)',
    'beverage soda dr pepper cherry ml': 'Soft drinks (ND)',
    'beverage soda root beer': 'Soft drinks (ND)',
    'beverage soda lemon lime flavored soda': 'Soft drinks (ND)',
    'beverage soda squirt thirst quencher grapefruit soda': 'Soft drinks (ND)',
    'beverage soda dr pepper': 'Soft drinks (ND)',
    'beverage soda fanta raspberry flavour': 'Soft drinks (ND)',
    'beverage soda coca cola classic': 'Soft drinks (ND)',
    'beverage soda fanta orange': 'Soft drinks (ND)',
    'beverage soda fanta orange ml': 'Soft drinks (ND)',
    'beverage soda sprite natural flavour': 'Soft drinks (ND)',
    'meat seafood poultry seara chicken franks': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'meat seafood shrimp shore mariner cooked vannamei whole prawns': 'Other seafood, live, fresh, chilled or frozen (ND)',
    'meat seafood poultry chicken leg quarter puha moa': 'Meat, fresh, chilled or frozen (ND)',
    'meat seafood mussel westpac green shell mussels': 'Other seafood, live, fresh, chilled or frozen (ND)',
    'beverage water aqua dew pure water bottle pack': 'Water (ND)',
    'grocery instant food maggi flavoured noodles': 'Ready-made food (ND)',
    'beverage soda sprite': 'Soft drinks (ND)',
    'beverage soda sprite can ml': 'Soft drinks (ND)',
    'beverage soda fanta pineapple flavour': 'Soft drinks (ND)',
    'grocery punjas breakfast crackers': 'Bread and bakery products (ND)',
    'meat seafood sausage hellers chunky cheese': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'personal care oral care colgate toothpaste maximum cavity protection': 'Other appliances, articles and products for personal care (ND)',
    'meat seafood mussel sea breeze frozen raw oysters': 'Other seafood, live, fresh, chilled or frozen (ND)',
    'beverage water fiji water bottle box': 'Water (ND)',
    'grocery instant food maruchan fire yakisoba spicy beef flavor': 'Ready-made food (ND)',
    'grocery canned food wattie spaghetti tomato sauce': 'Ready-made food (ND)',
    'grocery instant food welch gelatin concord grape': 'Other sugar confectionery and desserts n.e.c. (ND)',
    'grocery instant food maggie minute noodle chicken flavour': 'Ready-made food (ND)',
    'grocery sb chunky vegetable medley': 'Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations (ND)',
    'meat seafood sausage hellers breakfast sausage': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'personal care oral care colgate anticavity toothpaste': 'Other appliances, articles and products for personal care (ND)',
    'personal care oral care colgate max fresh peppermint ice': 'Other appliances, articles and products for personal care (ND)',
    'personal care oral care lukcy super soft mouthwash winter green': 'Other appliances, articles and products for personal care (ND)',
    'personal care oral care lucky super soft mouth wash original': 'Other appliances, articles and products for personal care (ND)',
    'grocery canned food hormel spam classic': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'grocery canned food pams apples sliced': 'Fruits and nuts, ground, and in other preparations (ND)',
    'grocery canned food woolsworths pineapple crushed juice': 'Fruits and nuts, ground, and in other preparations (ND)',
    'grocery best foods mayonnaise': 'Salt, condiments and sauces (ND)',
    'grocery baking golden harvest baking powder': 'Other food products n.e.c. (ND)',
    'grocery herbs gregg lemon grass powder': 'Spices, culinary herbs and seeds (ND)',
    'grocery canned food woolsworths pineapple juice': 'Fruits and nuts, ground, and in other preparations (ND)',
    'grocery canned food woolsworths pineapple slices juice': 'Fruits and nuts, ground, and in other preparations (ND)',
    'grocery canned food pams diced tomatoes chilli herb': 'Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations (ND)',
    'grocery canned food kara coconut cream': 'Other food products n.e.c. (ND)',
    'grocery canned food pams halved apricots juice': 'Fruits and nuts, ground, and in other preparations (ND)',
    'grocery canned food sun bell tuna chunks oil added': 'Fish preparations (ND)',
    'grocery canned food old capital special tuna flakes': 'Fish preparations (ND)',
    'grocery baking spice time food colors': 'Other food products n.e.c. (ND)',
    'grocery herbs spice supreme dill seeds': 'Spices, culinary herbs and seeds (ND)',
    'grocery herbs spice supreme pure ground sage': 'Spices, culinary herbs and seeds (ND)',
    'grocery herbs spice supreme oregano leaves': 'Spices, culinary herbs and seeds (ND)',
    'grocery herbs pams moroccan capers': 'Spices, culinary herbs and seeds (ND)',
    'personal care body wash olay body wash shea butter': 'Other appliances, articles and products for personal care (ND)',
    'grocery bolis icesticks': 'Ice, ice cream and sorbets (ND)',
    'grocery baking bake fresh baking cups cups': 'Other non-durable household goods (ND)',
    'grocery baking cadbury baking cocoa': 'Chocolate, cocoa and cocoa-based food products (ND)',
    'grocery baking pams cocoa powder': 'Chocolate, cocoa and cocoa-based food products (ND)',
    'grocery baking edmonds fielder cornflour': 'Flour of cereals (ND)',
    'grocery baking pams dark compound chocolate drops': 'Chocolate, cocoa and cocoa-based food products (ND)',
    'grocery baking pillsbury traditional chocolate cake mix': 'Other milled cereal and grain products (ND)',
    'grocery baking arm hammer baking soda': 'Other food products n.e.c. (ND)',
    'grocery spread pams plum jam': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'personal care hair care palmolive luminous oil argan oil': 'Other appliances, articles and products for personal care (ND)',
    'personal care body wash olay body wash ultra moisture': 'Other appliances, articles and products for personal care (ND)',
    'personal care body wash dove showergel talco': 'Other appliances, articles and products for personal care (ND)',
    'grocery canned food sun bell tuna chunks': 'Fish preparations (ND)',
    'grocery canned food ocean queen mackerel tomato sauce': 'Fish preparations (ND)',
    'grocery canned food ocean queen mackerel natural oil': 'Fish preparations (ND)',
    'grocery canned food wattie chicken corn soup': 'Ready-made food (ND)',
    'grocery spread pams apricot jam': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'personal care hair care head shoulders shampoo anti hairfall': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care palmolive intensive moisture conditioner': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care palmolive actve nourishment shampoo': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care conditioner herbal escapes ocean refresh': 'Other appliances, articles and products for personal care (ND)',
    'beverage tea punjas classic masala chai tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'grocery sauce del monte ketchup': 'Salt, condiments and sauces (ND)',
    'beverage coffee creamer nestle coffee mate original': 'Other dairy products (ND)',
    'grocery cereal nestle koko krunch': 'Breakfast cereals (ND)',
    'personal care hair care head shoulders conditioner supreme smooth': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care suave shampoo sun ripened strawberry': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care garnier fructis elastic curls hair comb': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care garnier fructis liso coco': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care suave shampoo wild cherry': 'Other appliances, articles and products for personal care (ND)',
    'beverage tea naturate lemon grass': 'Tea, maté and other plant-derived products for infusion (ND)',
    'grocery sauce woolworths sauce': 'Salt, condiments and sauces (ND)',
    'beverage juice nectar langers juice': 'Fruit and vegetable juices (ND)',
    'grocery cereal ricies oven popped rice': 'Breakfast cereals (ND)',
    'grocery cereal cheerios multi grain': 'Breakfast cereals (ND)',
    'grocery cereal kellogg cereal krave double chocolate brownie batter': 'Breakfast cereals (ND)',
    'grocery cereal kellogg cereal krave chocolate': 'Breakfast cereals (ND)',
    'grocery cereal kellogg cereal raisin bran crunch': 'Breakfast cereals (ND)',
    'grocery woolworths barbecue sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce san remo alfredo pasta sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce americana mushroom soy sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce americana light soy sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce dyc white vinegar': 'Salt, condiments and sauces (ND)',
    'grocery sauce madame wont sweet chilli': 'Salt, condiments and sauces (ND)',
    'grocery sauce madame wong hot chilli sriracha sauce': 'Salt, condiments and sauces (ND)',
    'grocery pasta allegra macaroni penne rigate': 'Macaroni, noodles, couscous and similar pasta products (ND)',
    'grocery sauce pams sweet sour simmer sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce del monte sloppy joe': 'Salt, condiments and sauces (ND)',
    'grocery sauce wattie tomato sauce': 'Salt, condiments and sauces (ND)',
    'grocery sauce hunts pasta sauce roasted garlic onion': 'Salt, condiments and sauces (ND)',
    'grocery sauce royal lemon blend': 'Salt, condiments and sauces (ND)',
    'grocery sauce tabasco': 'Salt, condiments and sauces (ND)',
    'beverage tea naturate seven blossoms': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea grand harvest brand green tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'grocery pasta kraft macaroni cheese original': 'Ready-made food (ND)',
    'grocery pasta allegra rotini num': 'Macaroni, noodles, couscous and similar pasta products (ND)',
    'beverage tea twinings pure green tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings morning tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings pure peppermint': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings lemon ginger': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings english breakfast': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings new zealand breakfast': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea punjas pure ceylon tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea lipton black tea': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea naturate hibicus jamaica': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings london lady grey': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings earl grey': 'Tea, maté and other plant-derived products for infusion (ND)',
    'beverage tea twinings london green tea jasmine': 'Tea, maté and other plant-derived products for infusion (ND)',
    'personal care hair care tresemme shampoo damage repair': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care tresemme shampoo macadamia oil': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care tresemme shampoo coconut milk': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care tresemme botanique shampoo': 'Other appliances, articles and products for personal care (ND)',
    'personal care hair care tresemme shampoo shea butter': 'Other appliances, articles and products for personal care (ND)',
    'grocery spread pams blackcurrant jam': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'grocery spread value creamed clover blend honey': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'grocery spread pams creamed clover honey': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'grocery spread pams creamed manuka honey': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'grocery spread pams squeezable liquid honey': 'Jams, marmalades, fruit jellies, purées and pastes, and honey (ND)',
    'grocery spread vegemite spread': 'Other food products n.e.c. (ND)',
    'grocery canned food palm corned beef': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'personal care oral care listerine fresh burst': 'Other appliances, articles and products for personal care (ND)',
    'meat seafood sausage hellers trusty bbq precooked sausages': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'meat seafood sausage hellers chinese honey sausage': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'meat seafood sausage seara chicken sausage ctn': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
    'grocery seasoning mccormick himalayan pink salt': 'Salt, condiments and sauces (ND)',
    'grocery beans sunvista red kidney beans': 'Pulses (ND)',
    'grocery baking pams icing sugar': 'Cane sugar and beet sugar (ND)',
    'grocery pasta coles penne rigate': 'Macaroni, noodles, couscous and similar pasta products (ND)',
    'grocery seasoning sal bahia iodized sea salt': 'Salt, condiments and sauces (ND)',
    'grocery canned food armour treet original': 'Preparations of meat, offal, blood and other parts of slaughtered animals (ND)',
}


def get_coicop_details(product_w_cat):
    if ';' not in product_w_cat:
        parts = product_w_cat.split(' ')
        prod_name = " ".join(parts[:-1])
        cat_str = parts[-1]
    else:
        prod_name, cat_str = product_w_cat.split(';', 1)
    
    cat_str = cat_str.strip()
    
    coicop_title = category_mapping.get(cat_str)
    
    if coicop_title:
        code = title_to_code.get(coicop_title)
        if code:
            return code, coicop_title_map.get(code, '')
            
    return '', ''

# Apply the function to the dataframe
mis_prods[['code', 'title']] = mis_prods['product_w_cat'].apply(
    lambda x: pd.Series(get_coicop_details(x))
)

# Save the result
mis_prods.to_csv('mis_classed2.csv', index=False)

print("CSV 'mis_classed2.csv' created successfully.")
