"""Frozen PRE-reorg tier-a composition oracle (Phase 01.66 / Plan 01, SC4).

This module captures the TRUE current live composition of the regex_patterns tree
as plain literals, generated by running the live composer once on the pre-reorg
tree (commit-state before any SCREAMING_SNAKE rename or file move). Because nothing
has been renamed or relocated yet, the live composer output IS the pre-reorg truth.

Two surfaces are frozen:

  1. Per-kind id sequences (KIND_BASELINE) — exactly what
     ``dict_view.regex_units_for_extract`` / ``pack_patterns_for_normalize`` /
     ``_ids_for_kind`` emit today, kind-by-kind, in declaration order. The canon
     tuple INCLUDES ``multipack_pc_glued_en`` at index 3 (a canon pattern added
     2026-06-25 that the stale GOLDEN_CANON literal in test_regex_patterns_layout.py
     omitted) — this fixture is the trustworthy baseline, NOT that stale literal.

  2. The ``load_for`` selection sweep (LOAD_FOR_BASELINE) — for a representative
     (country, lang) sweep, the composed id sequence from
     ``_registry.load_for(country, lang)``. There are no country patch packages
     today, so the sweep is over country=None with lang in the resolvable set.

This is the pre-reorg oracle consumed by test_composition_diff.py. The stale
GOLDEN_CANON must NOT be trusted as the baseline.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Per-kind composed id sequences (dict_view surface) — frozen pre-reorg.
# Captured via:
#   from prices.enrich.regex_patterns.dict_view import _ids_for_kind
#   _ids_for_kind("canon"), _ids_for_kind("extra_unit"), ...
# ---------------------------------------------------------------------------

CANON: tuple[str, ...] = (
    "multipack_num_x_value_unit",
    "multipack_value_unit_x_count",
    "multipack_pcs_en",
    "multipack_pc_glued_en",
    "multipack_n_x_only",
    "multipack_vi_loc",
    "multipack_vi_count_unit",
    "multipack_zh_count_unit",
    "multipack_ja_kana_set",
    "value_unit_volume_mass",
    "zh_volume_mass",
)

EXTRA_UNITS: tuple[str, ...] = ("cl_volume", "vi_lit_volume")

EXTRA_COUNT: tuple[str, ...] = (
    "cjk_mai",
    "cjk_pair",
    "cjk_grain",
    "cjk_strip",
    "cjk_sheet_tissue",
    "cjk_set_group",
    "cjk_numeral_set",
    "vi_to_sheets",
    "cjk_ko_pcs",
    "cjk_n_x_count",
    "cjk_double_pack",
    "en_caps",
    "en_tablets",
    "en_sachets_s",
    "en_sheets",
    "en_pack_of",
    "en_n_pack",
    "en_n_individual_pack",
    "en_half_dozen",
    "en_dozen",
    "en_twin_pack",
    "en_triple_pack",
    "en_double_pack",
    "vi_m_pieces",
    "en_n_rolls",
    "en_comma_xn",
    "en_n_pcs",
    "en_apos_s",
    "en_n_tickets",
)

MULTI_PACK: tuple[str, ...] = (
    "cjk_inner_outer_star",
    "cjk_inner_outer_full",
)

PRICING_BASIS_MARKERS: tuple[str, ...] = (
    "en_per_kg_parens",
    "en_per_kg_bare",
    "en_per_l_parens",
    "en_per_liter_bare",
)

# `cjk_numeral_version` is a live PATTERN in the tree but is deliberately NOT
# routed into any consumed bucket (dict_view dropped it from extra_count
# 2026-06-16). It is a real registry id, so it is part of the rename surface.
UNROUTED: tuple[str, ...] = ("cjk_numeral_version",)

# Kind name (the PackPattern.kind value) -> frozen id sequence. Keys match the
# `kind` field values consumed by dict_view._ids_for_kind.
KIND_BASELINE: dict[str, tuple[str, ...]] = {
    "canon": CANON,
    "extra_unit": EXTRA_UNITS,
    "extra_count": EXTRA_COUNT,
    "multi_pack": MULTI_PACK,
    "pricing_basis_marker": PRICING_BASIS_MARKERS,
    "unrouted": UNROUTED,
}

# ---------------------------------------------------------------------------
# load_for selection sweep — frozen pre-reorg.
# Captured via:
#   from prices.enrich.regex_patterns._registry import load_for
#   tuple(p.id for p in load_for(country, lang))
# No country patch packages exist today, so the sweep is country=None over the
# resolvable lang set plus the lang=None broad fallback.
# ---------------------------------------------------------------------------

LOAD_FOR_BASELINE: dict[tuple[str | None, str | None], tuple[str, ...]] = {
    (None, "en"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "multipack_pcs_en",
        "multipack_pc_glued_en",
        "en_per_kg_parens",
        "en_per_kg_bare",
        "en_per_l_parens",
        "en_per_liter_bare",
        "en_caps",
        "en_tablets",
        "en_sachets_s",
        "en_sheets",
        "en_pack_of",
        "en_n_pack",
        "en_n_individual_pack",
        "en_twin_pack",
        "en_triple_pack",
        "en_double_pack",
    ),
    (None, "zh"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "multipack_zh_count_unit",
        "zh_volume_mass",
        "cjk_mai",
        "cjk_pair",
        "cjk_grain",
        "cjk_strip",
        "cjk_sheet_tissue",
        "cjk_set_group",
        "cjk_numeral_version",
        "cjk_numeral_set",
        "cjk_ko_pcs",
        "cjk_n_x_count",
        "cjk_double_pack",
        "cjk_inner_outer_star",
        "cjk_inner_outer_full",
    ),
    (None, "ja"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "multipack_ja_kana_set",
        "cjk_mai",
        "cjk_pair",
        "cjk_grain",
        "cjk_strip",
        "cjk_sheet_tissue",
        "cjk_set_group",
        "cjk_numeral_version",
        "cjk_numeral_set",
        "cjk_ko_pcs",
        "cjk_n_x_count",
        "cjk_double_pack",
        "cjk_inner_outer_star",
        "cjk_inner_outer_full",
    ),
    (None, "ko"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "cjk_mai",
        "cjk_pair",
        "cjk_grain",
        "cjk_strip",
        "cjk_sheet_tissue",
        "cjk_set_group",
        "cjk_numeral_version",
        "cjk_numeral_set",
        "cjk_ko_pcs",
        "cjk_n_x_count",
        "cjk_double_pack",
        "cjk_inner_outer_star",
        "cjk_inner_outer_full",
    ),
    (None, "vi"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "vi_m_pieces",
        "multipack_vi_loc",
        "multipack_vi_count_unit",
        "en_caps",
        "en_tablets",
        "en_sachets_s",
        "en_sheets",
        "en_pack_of",
        "en_n_pack",
        "en_n_individual_pack",
        "en_twin_pack",
        "en_triple_pack",
        "en_double_pack",
    ),
    (None, "id"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "en_caps",
        "en_tablets",
        "en_sachets_s",
        "en_sheets",
        "en_pack_of",
        "en_n_pack",
        "en_n_individual_pack",
        "en_twin_pack",
        "en_triple_pack",
        "en_double_pack",
    ),
    (None, "ms"): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "en_caps",
        "en_tablets",
        "en_sachets_s",
        "en_sheets",
        "en_pack_of",
        "en_n_pack",
        "en_n_individual_pack",
        "en_twin_pack",
        "en_triple_pack",
        "en_double_pack",
    ),
    (None, None): (
        "en_n_rolls",
        "en_comma_xn",
        "en_n_pcs",
        "en_apos_s",
        "en_n_tickets",
        "cl_volume",
        "vi_lit_volume",
        "multipack_num_x_value_unit",
        "multipack_value_unit_x_count",
        "multipack_n_x_only",
        "value_unit_volume_mass",
        "vi_to_sheets",
        "multipack_pcs_en",
        "multipack_pc_glued_en",
        "en_per_kg_parens",
        "en_per_kg_bare",
        "en_per_l_parens",
        "en_per_liter_bare",
        "multipack_ja_kana_set",
        "vi_m_pieces",
        "multipack_vi_loc",
        "multipack_vi_count_unit",
        "multipack_zh_count_unit",
        "zh_volume_mass",
        "cjk_mai",
        "cjk_pair",
        "cjk_grain",
        "cjk_strip",
        "cjk_sheet_tissue",
        "cjk_set_group",
        "cjk_numeral_version",
        "cjk_numeral_set",
        "cjk_ko_pcs",
        "cjk_n_x_count",
        "cjk_double_pack",
        "cjk_inner_outer_star",
        "cjk_inner_outer_full",
        "en_caps",
        "en_tablets",
        "en_sachets_s",
        "en_sheets",
        "en_pack_of",
        "en_n_pack",
        "en_n_individual_pack",
        "en_twin_pack",
        "en_triple_pack",
        "en_double_pack",
    ),
}
