from pathlib import Path

# Model
MODEL_NAME = "gemini-3.1-flash-lite"
BATCH_SIZE = 15
CONCURRENCY = 1
OUTPUT_RETRIES = 3

# Paths (relative to repo root)
REPO_ROOT = Path(__file__).resolve().parents[3]
RAW_PRICES_CSV = REPO_ROOT / "outputs" / "prices" / "raw" / "raw_prices.csv"
ENRICHED_PRICES_CSV = (
    REPO_ROOT / "outputs" / "prices" / "enriched" / "enriched_prices.csv"
)
ENRICH_DIR = REPO_ROOT / "data" / "prices" / "_enrich"
PRODUCTS_INPUT_PARQUET = ENRICH_DIR / "products_input.parquet"
PRODUCTS_PARQUET = ENRICH_DIR / "products.parquet"
MATCH_LOG_PARQUET = ENRICH_DIR / "match_log.parquet"
MATCH_FUZZY_ENABLED = False
COICOP_XLSX = ENRICH_DIR / "coicop_categories.xlsx"
COICOP_SUBCATS_JSON = (
    Path(__file__).resolve().parent / "static" / "coicop_subcategories.json"
)
CACHE_DIR = ENRICH_DIR / "cache"
ENRICHMENTS_PARQUET = CACHE_DIR / "enrichments.parquet"
FAILED_PARQUET = CACHE_DIR / "_failed.parquet"
EVAL_SET_CSV = ENRICH_DIR / "eval_set.csv"
EVAL_HISTORY_CSV = ENRICH_DIR / "eval_history.csv"

PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"
ENRICH_PROMPT_PATH = PROMPTS_DIR / "enrich_system.md"
TAXONOMY_PROMPT_PATH = PROMPTS_DIR / "taxonomy_system.md"

# Tier (b) — embed + cluster-resolved KNN
EMBED_BACKEND = "e5"  # "gemini" | "e5"
EMBED_MODEL_GEMINI = "gemini-embedding-001"
EMBED_DIM = 768
EMBED_RPM = 90  # free-tier ceiling is 100/min for gemini-embedding-001
KNN_K = 5
KNN_TAU_HIGH = 0.92
KNN_TAU_LOW = 0.85
KNN_CLUSTER_AGREEMENT_MIN = 0.90
KNN_SOFT_MAJORITY_MIN = 3  # out of K=5
KNN_BOOTSTRAP_CLUSTER_FLOOR = 150  # was 200; lowered post-sanitization to retain SG/MY indices (5k eval, 2026-06-11)
MATCH_TIER_B_ENABLED = True

# Channel-aware KNN: over-fetch by this factor to give the channel filter
# enough candidates to keep, then keep only the same-channel ones if we have
# at least MIN_SAME_CHANNEL_KNN of them; otherwise fall through to
# cross-channel candidates (logged as cross_channel_accept=True).
KNN_CHANNEL_OVERFETCH = 4
MIN_SAME_CHANNEL_KNN = 3

TIER_B_INDEX_DIR = ENRICH_DIR / "_tier_b_index"
TIER_B_MISSES_PARQUET = ENRICH_DIR / "_tier_b_misses.parquet"
EMBED_CACHE_PATH = ENRICH_DIR / "_embed_cache.npz"

# Tier-b pool filter (Feature B, ADR-0003). Default "off" — bake-off favors
# rank_boost but the gold sample is too small to flip the production default
# without further validation. Values: "off" | "hard_drop" | "rank_boost".
TIER_B_POOL_FILTER = "off"
POOL_FILTER_BOOST = 0.05

# Channel-aware tier-c
CHANNEL_COICOP_PRIORS_PATH = (
    Path(__file__).resolve().parent / "static" / "channel_coicop_priors.yaml"
)
CHANNEL_OUTLIER_AUDIT = True
CHANNEL_OUTLIERS_PARQUET = ENRICH_DIR / "_channel_outliers.parquet"

# Tier-b kill-switch — combos with eval-measured precision below the floor
# are forced to tier-c. Static list regenerated by
# scripts/eval_5k_grades_to_killswitch.py.
TIER_B_KILLSWITCH_ENABLED = True
TIER_B_KILLSWITCH_PATH = (
    Path(__file__).resolve().parent / "static" / "tier_b_killswitch.yaml"
)

# Tier (c) — KNN-aware LLM reranker
LLM_MODEL_BASELINE = "gemini-3.1-flash-lite"
LLM_MODEL_ESCALATE = "gemini-3-pro"
LLM_TEMPERATURE = 0.0
LLM_CONFIDENCE_THRESHOLD = 0.7
