"""COICOP class 01 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="01",
    label="Food and non-alcoholic beverages",
    groups=(
        Group(
            code="01.1",
            label="Food",
            subgroups=(
                Subgroup(
                    code="01.1.1",
                    label="Cereals and cereal products",
                    leaves=(
                        Leaf(
                            code="01.1.1.1",
                            label="Cereals",
                            excludes=(
                                ExcludeRef(code="01.1.1.2", label="flour of cereals"),
                                ExcludeRef(code="01.1.1.4", label="breakfast cereals"),
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="cereal-based ready-made preparations such as-ready-made soups based on cereals",
                                ),
                                ExcludeRef(
                                    code="01.1.9.2",
                                    label="baby rice cereals and other baby cereals",
                                ),
                                ExcludeRef(code="09.3.1.2", label="seeds for planting"),
                            ),
                        ),
                        Leaf(
                            code="01.1.1.2",
                            label="Flour of cereals",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.9.2",
                                    label="flour as baby food, baby rice cereals and other baby cereals",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.1.3",
                            label="Bread and bakery products",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="pizza with topping, whether precooked or not; quiche; and meat and fish pies",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.1.4",
                            label="Breakfast cereals",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.1.5",
                            label="Macaroni, noodles, couscous and similar pasta products",
                            excludes=(
                                ExcludeRef(code="01.1.1.1", label="bulgur"),
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="prepared dishes containing stuffed pasta, and prepared couscous dishes",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.1.9",
                            label="Other milled cereal and grain products",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.7.9",
                                    label="soy meat and soy burgers, veggie burgers, tofu, tempeh and other meat substitutes made from vegetables and nuts; and potato starch, tapioca, sago and other starches",
                                ),
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="ready-made cereal-based preparations, such as ready-made cereal-based soups",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.2",
                    label="Live animals, and meat and other parts of slaughtered land animals",
                    leaves=(
                        Leaf(
                            code="01.1.2.1",
                            label="Live land animals",
                            excludes=(
                                ExcludeRef(code="01.1.3.1", label="live fish"),
                                ExcludeRef(code="01.1.3.4", label="other live seafood"),
                                ExcludeRef(
                                    code="07.1.4.0", label="live animals for transport"
                                ),
                                ExcludeRef(
                                    code="09.1.2.4",
                                    label="live animals purchased for recreational purposes",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.2.2",
                            label="Meat, fresh, chilled or frozen",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.2.3",
                            label="Meat, dried, salted, in brine or smoked",
                            excludes=(ExcludeRef(code="01.1.2.5", label="pâté"),),
                        ),
                        Leaf(
                            code="01.1.2.4",
                            label="Offal, blood and other parts of slaughtered animals, fresh, chilled or frozen, dried, salted, in brine or smoked",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.2.5",
                                    label="preparations of offal, blood and other parts of slaughtered animals",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.2.5",
                            label="Preparations of meat, offal, blood and other parts of slaughtered animals",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.3",
                    label="Fish and other seafood",
                    leaves=(
                        Leaf(
                            code="01.1.3.1",
                            label="Fish, live, fresh, chilled or frozen",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.3.7",
                                    label="meal, livers, roes, fins, maws and other offal",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.3.2",
                            label="Fish, dried, salted, in brine or smoked",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.3.7",
                                    label="meal, livers, roes, fins, maws and other offal",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.3.3",
                            label="Fish preparations",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.3.7",
                                    label="prepared or preserved livers, roes, fins and other offal",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.3.4",
                            label="Other seafood, live, fresh, chilled or frozen",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.7.4",
                                    label="seaweeds and other edible aquatic plants",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.3.5",
                            label="Other seafood, dried, salted, in brine or smoked",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.3.6",
                            label="Other seafood preparations",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.3.7",
                            label="Livers, roes and other offal of fish and of other seafood in all forms",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.7.4",
                                    label="seaweeds and other aquatic plants",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.4",
                    label="Milk, other dairy products and eggs",
                    leaves=(
                        Leaf(
                            code="01.1.4.1",
                            label="Raw and whole milk",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.6",
                                    label="curdled, fermented or acidified milk and cream",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.2",
                            label="Skimmed milk",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.4.3",
                            label="Other milk and cream",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.7",
                                    label="beverages flavoured with cocoa, coffee or other substances",
                                ),
                                ExcludeRef(
                                    code="01.1.9.2",
                                    label="condensed, evaporated and powdered milk used as baby food",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.4",
                            label="Non-animal milk",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.9.3", label="coconut milk for cooking"
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.5",
                            label="Cheese",
                            excludes=(ExcludeRef(code="01.1.7.9", label="tofu"),),
                        ),
                        Leaf(
                            code="01.1.4.6",
                            label="Yoghurt and similar products",
                            excludes=(
                                ExcludeRef(code="01.1.8.6", label="frozen yoghurt"),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.7",
                            label="Milk-based dessert and beverages",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.8.3",
                                    label="lemon curd and similar fruit card",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.8",
                            label="Eggs",
                            excludes=(
                                ExcludeRef(code="01.1.3.7", label="fish roe"),
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="omelettes, crêpes and other ready-made egg-based food products",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.4.9",
                            label="Other dairy products",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.5.2",
                                    label="butter and other oils and fats derived from milk",
                                ),
                                ExcludeRef(code="01.1.8.6", label="ice cream"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.5",
                    label="Oils and fats",
                    leaves=(
                        Leaf(
                            code="01.1.5.1",
                            label="Vegetable oils",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.5.2",
                            label="Butter and other oils and fats derived from milk",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.5.3",
                            label="Margarine and similar preparations",
                            excludes=(
                                ExcludeRef(code="01.1.8.4", label="peanut butter"),
                            ),
                        ),
                        Leaf(
                            code="01.1.5.9",
                            label="Other animal oils and fats",
                            excludes=(
                                ExcludeRef(
                                    code="06.1.1.1",
                                    label="cod liver or halibut liver oil",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.6",
                    label="Fruits and nuts",
                    leaves=(
                        Leaf(
                            code="01.1.6.1",
                            label="Dates, figs and tropical fruits, fresh",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.7.5",
                                    label="plantains and cooking bananas",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.6.2",
                            label="Citrus fruits, fresh",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.3",
                            label="Stone fruits and pome fruits, fresh",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.4",
                            label="Berries, fresh",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.5",
                            label="Other fruits, fresh",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.6",
                            label="Fruits, frozen",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.7",
                            label="Fruits, dried and dehydrated",
                            excludes=(
                                ExcludeRef(code="01.1.6.9", label="fruit flour"),
                            ),
                        ),
                        Leaf(
                            code="01.1.6.8",
                            label="Nuts, in shell or shelled",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.6.9",
                            label="Fruits and nuts, ground, and in other preparations",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.8.3",
                                    label="jams, marmalades, fruit jellies, purées and pastes",
                                ),
                                ExcludeRef(
                                    code="01.1.8.4",
                                    label="nut purées, nut butters and nut pastes",
                                ),
                                ExcludeRef(
                                    code="01.1.9.2",
                                    label="homogenized baby food preparations",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.7",
                    label="Vegetables, tubers, plantains, cooking bananas and pulses",
                    leaves=(
                        Leaf(
                            code="01.1.7.1",
                            label="Leafy or stem vegetables, fresh or chilled",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.2",
                            label="Fruit-bearing vegetables, fresh or chilled",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.3",
                            label="Green leguminous vegetables, fresh or chilled",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.4",
                            label="Other vegetables, fresh or chilled",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.5",
                            label="Tubers, plantains and cooking bananas, fresh or chilled",
                            excludes=(
                                ExcludeRef(code="01.1.6.1", label="dessert bananas"),
                            ),
                        ),
                        Leaf(
                            code="01.1.7.6",
                            label="Pulses",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.7",
                            label="Other vegetables, tubers, plantains and cooking bananas, dried and dehydrated",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.7.8",
                            label="Vegetables, tubers, plantains and cooking bananas, frozen",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.7.9",
                                    label="preparations such as frozen chipped potatoes",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.7.9",
                            label="Vegetables, tubers, plantains, cooking bananas and pulses, ground, and in other preparations",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.1.9",
                                    label="seitan and other meat substitutes made from cereals",
                                ),
                                ExcludeRef(
                                    code="01.1.9.1",
                                    label="ready-made vegetable preparations, whether frozen or not, including other ingredients, such as cheese, meat or fish; and ready-made soups",
                                ),
                                ExcludeRef(
                                    code="01.1.9.2",
                                    label="homogenized baby food preparations",
                                ),
                                ExcludeRef(
                                    code="01.1.9.4", label="culinary herbs and spices"
                                ),
                                ExcludeRef(
                                    code="01.1.9.9",
                                    label="broths and stocks containing vegetables",
                                ),
                                ExcludeRef(code="01.2.1.0", label="vegetable juices"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.8",
                    label="Sugar, confectionery and desserts",
                    leaves=(
                        Leaf(
                            code="01.1.8.1",
                            label="Cane sugar and beet sugar",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.8.2",
                                    label="refined cane or beet sugar, containing added flavouring or colouring matter",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.8.2",
                            label="Other sugars and sugar substitutes",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.8.3",
                            label="Jams, marmalades, fruit jellies, purées and pastes, and honey",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.8.4",
                            label="Nut purées, nut butters and nut pastes",
                            excludes=(),
                        ),
                        Leaf(
                            code="01.1.8.5",
                            label="Chocolate, cocoa and cocoa-based food products",
                            excludes=(
                                ExcludeRef(code="01.1.8.9", label="white chocolate"),
                                ExcludeRef(
                                    code="01.2.4.0",
                                    label="cocoa and chocolate-based drinks",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.8.6",
                            label="Ice, ice cream and sorbets",
                            excludes=(
                                ExcludeRef(code="04.5.5.0", label="ice for cooling"),
                            ),
                        ),
                        Leaf(
                            code="01.1.8.9",
                            label="Other sugar confectionery and desserts n.e.c.",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.8.5",
                                    label="sugar confectionery based on cocoa and chocolate",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.1.9",
                    label="Ready-made food and other food products",
                    leaves=(
                        Leaf(
                            code="01.1.9.1",
                            label="Ready-made food",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.1.3",
                                    label="bread and bakery products, and cakes",
                                ),
                                ExcludeRef(
                                    code="01.1.1.5",
                                    label="macaroni, noodles, couscous and similar pasta products uncooked, whether stuffed or not",
                                ),
                                ExcludeRef(
                                    code="01.1.7.9", label="chipped potatoes, frozen"
                                ),
                                ExcludeRef(
                                    code="01.1.8.9",
                                    label="ice cream (0.1.1.8.6) and other desserts, n.e.c.",
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.9.2",
                            label="Baby food",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.3",
                                    label="powdered milk not intended exclusively for baby use",
                                ),
                                ExcludeRef(
                                    code="01.1.4.6", label="yoghurt for children"
                                ),
                            ),
                        ),
                        Leaf(
                            code="01.1.9.3",
                            label="Salt, condiments and sauces",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.4", label="coconut milk for drinking"
                                ),
                                ExcludeRef(code="01.1.6.9", label="fruit pickles"),
                                ExcludeRef(code="01.1.7.9", label="vegetable pickles"),
                            ),
                        ),
                        Leaf(
                            code="01.1.9.4",
                            label="Spices, culinary herbs and seeds",
                            excludes=(
                                ExcludeRef(code="01.1.5.1", label="vegetable oils"),
                                ExcludeRef(code="09.3.1.2", label="seeds for planting"),
                            ),
                        ),
                        Leaf(
                            code="01.1.9.9",
                            label="Other food products n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="01.2",
            label="Non-alcoholic beverages",
            subgroups=(
                Subgroup(
                    code="01.2.1",
                    label="Fruit and vegetable juices",
                    leaves=(
                        Leaf(
                            code="01.2.1.0",
                            label="Fruit and vegetable juices",
                            excludes=(
                                ExcludeRef(code="01.2.6.0", label="sparkling juices"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.2",
                    label="Coffee and coffee substitutes",
                    leaves=(
                        Leaf(
                            code="01.2.2.0",
                            label="Coffee and coffee substitutes",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.7",
                                    label="milk-based beverages flavoured with coffee",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.3",
                    label="Tea, maté and other plant-derived products for infusion",
                    leaves=(
                        Leaf(
                            code="01.2.3.0",
                            label="Tea, maté and other plant-derived products for infusion",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.4",
                    label="Cocoa drinks",
                    leaves=(
                        Leaf(
                            code="01.2.4.0",
                            label="Cocoa drinks",
                            excludes=(
                                ExcludeRef(
                                    code="01.1.4.7",
                                    label="milk flavoured with chocolate or cacao",
                                ),
                                ExcludeRef(
                                    code="01.1.8.5",
                                    label="cocoa powder for all purposes; chocolate in bars or slabs; cocoa-based foods and cocoa-based dessert preparations",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.5",
                    label="Water",
                    leaves=(
                        Leaf(
                            code="01.2.5.0",
                            label="Water",
                            excludes=(
                                ExcludeRef(code="01.2.9.0", label="flavoured water"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.6",
                    label="Soft drinks",
                    leaves=(
                        Leaf(
                            code="01.2.6.0",
                            label="Soft drinks",
                            excludes=(
                                ExcludeRef(code="01.2.3.0", label="iced tea"),
                                ExcludeRef(code="01.2.5.0", label="sparkling water"),
                                ExcludeRef(code="01.2.9.0", label="flavoured water"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="01.2.9",
                    label="Other non-alcoholic beverages",
                    leaves=(
                        Leaf(
                            code="01.2.9.0",
                            label="Other non-alcoholic beverages",
                            excludes=(
                                ExcludeRef(
                                    code="01.2.1.0",
                                    label="syrups of fruit and vegetables and concentrates of fruit and vegetables",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="01.3",
            label="Services for processing primary goods for food and non-alcoholic beverages",
            subgroups=(
                Subgroup(
                    code="01.3.0",
                    label="Services for processing primary goods for food and non-alcoholic beverages",
                    leaves=(
                        Leaf(
                            code="01.3.0.0",
                            label="Services for processing primary goods for food and non-alcoholic beverages",
                            excludes=(
                                ExcludeRef(
                                    code="02.2.0.0",
                                    label="fruit and vegetable crushing and pressing services for the production of alcoholic beverages",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
