"""COICOP class 02 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="02",
    label="Alcoholic beverages, tobacco and narcotics",
    groups=(
        Group(
            code="02.1",
            label="Alcoholic beverages",
            subgroups=(
                Subgroup(
                    code="02.1.1",
                    label="Spirits and liquors",
                    leaves=(
                        Leaf(
                            code="02.1.1.0",
                            label="Spirits and liquors",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="02.1.2",
                    label="Wine",
                    leaves=(
                        Leaf(
                            code="02.1.2.1",
                            label="Wine from grapes",
                            excludes=(),
                        ),
                        Leaf(
                            code="02.1.2.2",
                            label="Wine from other sources",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="02.1.3",
                    label="Beer",
                    leaves=(
                        Leaf(
                            code="02.1.3.0",
                            label="Beer",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="02.1.9",
                    label="Other alcoholic beverages",
                    leaves=(
                        Leaf(
                            code="02.1.9.0",
                            label="Other alcoholic beverages",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="02.2",
            label="Alcohol production services",
            subgroups=(
                Subgroup(
                    code="02.2.0",
                    label="Alcohol production services",
                    leaves=(
                        Leaf(
                            code="02.2.0.0",
                            label="Alcohol production services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="02.3",
            label="Tobacco",
            subgroups=(
                Subgroup(
                    code="02.3.0",
                    label="Tobacco",
                    leaves=(
                        Leaf(
                            code="02.3.0.1",
                            label="Cigarettes",
                            excludes=(),
                        ),
                        Leaf(
                            code="02.3.0.2",
                            label="Cigars",
                            excludes=(),
                        ),
                        Leaf(
                            code="02.3.0.9",
                            label="Other tobacco products",
                            excludes=(
                                ExcludeRef(
                                    code="11.1.1",
                                    label="tobacco that is consumed through use of a shisha or a hookah pipe in restaurants, cafés or shisha lounges",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="02.4",
            label="Narcotics",
            subgroups=(
                Subgroup(
                    code="02.4.0",
                    label="Narcotics",
                    leaves=(
                        Leaf(
                            code="02.4.0.0",
                            label="Narcotics",
                            excludes=(
                                ExcludeRef(
                                    code="06.1.1.1",
                                    label="narcotics used for medicinal purpose",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
