"""COICOP class 03 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="03",
    label="Clothing and footwear",
    groups=(
        Group(
            code="03.1",
            label="Clothing",
            subgroups=(
                Subgroup(
                    code="03.1.1",
                    label="Clothing materials",
                    leaves=(
                        Leaf(
                            code="03.1.1.0",
                            label="Clothing materials",
                            excludes=(
                                ExcludeRef(code="05.2.1.1", label="furnishing fabrics"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="03.1.2",
                    label="Garments",
                    leaves=(
                        Leaf(
                            code="03.1.2.1",
                            label="Garments for men or boys",
                            excludes=(
                                ExcludeRef(
                                    code="03.1.2.3",
                                    label="garments for infants (under 2 years of age)",
                                ),
                                ExcludeRef(
                                    code="03.1.4.2",
                                    label="tailoring services for which the customer supplies the material",
                                ),
                                ExcludeRef(
                                    code="06.1.2.2",
                                    label="articles of medical hosiery, such as elasticated stockings",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.1.2.2",
                            label="Garments for women or girls",
                            excludes=(
                                ExcludeRef(
                                    code="03.1.2.3",
                                    label="garments for infants (under 2 years of age)",
                                ),
                                ExcludeRef(
                                    code="03.1.4.2",
                                    label="tailoring services for which the customer supplies the material",
                                ),
                                ExcludeRef(
                                    code="06.1.2.2",
                                    label="articles of medical hosiery, such as elasticated stockings",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.1.2.3",
                            label="Garments for infants (under 2 years of age)",
                            excludes=(
                                ExcludeRef(
                                    code="03.1.4.2",
                                    label="tailoring services for which the customer supplies the material",
                                ),
                                ExcludeRef(
                                    code="13.2.9.1",
                                    label="diapers (nappies) of any material",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.1.2.4",
                            label="School uniforms",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="03.1.3",
                    label="Other articles of clothing and clothing accessories",
                    leaves=(
                        Leaf(
                            code="03.1.3.1",
                            label="Other articles of clothing",
                            excludes=(
                                ExcludeRef(
                                    code="05.6.1.9",
                                    label="pins, safety pins, sewing needles, knitting needles and thimbles; rubber gloves and other articles made of rubber; and gardening gloves",
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="protective headgear for sports; and other protective gear for sports, such as life jackets, boxing and other sporting gloves, body padding, belts, supports, etc.",
                                ),
                                ExcludeRef(
                                    code="13.1.2.0", label="paper handkerchiefs"
                                ),
                                ExcludeRef(
                                    code="13.2.1.1",
                                    label="watches, jewellery, cufflinks and tiepins",
                                ),
                                ExcludeRef(
                                    code="13.2.9.1",
                                    label="umbrellas and parasols, fans and key rings",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.1.3.2",
                            label="Clothing accessories",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="03.1.4",
                    label="Cleaning, repair, tailoring and hire of clothing",
                    leaves=(
                        Leaf(
                            code="03.1.4.1",
                            label="Cleaning of clothing",
                            excludes=(
                                ExcludeRef(
                                    code="05.6.2.9",
                                    label="dry-cleaning, laundering, dyeing of household linen and other household textiles",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.1.4.2",
                            label="Repair, tailoring and hire of clothing",
                            excludes=(
                                ExcludeRef(
                                    code="05.2.2.0",
                                    label="repair, hire and sewing services of household linen and other household textiles",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="03.2",
            label="Footwear",
            subgroups=(
                Subgroup(
                    code="03.2.1",
                    label="Shoes and other footwear",
                    leaves=(
                        Leaf(
                            code="03.2.1.1",
                            label="Footwear for men",
                            excludes=(
                                ExcludeRef(
                                    code="03.2.2.0",
                                    label="cleaning, repair and hire of footwear",
                                ),
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="polishes, creams and other shoe-cleaning articles",
                                ),
                                ExcludeRef(
                                    code="06.1.3.3", label="therapeutic footwear"
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="game-specific footwear (ski boots, football boots, golfing shoes and other such footwear fitted with ice skates, rollers, spikes, studs, etc.); and shin guards, cricket pads and other such protective sports apparel",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.2.1.2",
                            label="Footwear for women",
                            excludes=(
                                ExcludeRef(
                                    code="03.2.2.0",
                                    label="cleaning, repair and hire of footwear",
                                ),
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="polishes, creams and other shoe-cleaning articles",
                                ),
                                ExcludeRef(
                                    code="06.1.3.3", label="therapeutic footwear"
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="game-specific footwear (ski boots, football boots, golfing shoes and other such footwear fitted with ice skates, rollers, spikes, studs, etc.); and shin guards, cricket pads and other such protective sports apparel",
                                ),
                            ),
                        ),
                        Leaf(
                            code="03.2.1.3",
                            label="Footwear for infants and children",
                            excludes=(
                                ExcludeRef(
                                    code="03.2.2.0",
                                    label="cleaning, repair and hire of footwear",
                                ),
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="polishes, creams and other shoe-cleaning articles",
                                ),
                                ExcludeRef(
                                    code="06.1.3.3", label="therapeutic footwear"
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="game-specific footwear (ski boots, football boots, golfing shoes and other such footwear fitted with ice skates, rollers, spikes, studs, etc.); and shin guards, cricket pads and other such protective sports apparel",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="03.2.2",
                    label="Cleaning, repair and hire of footwear",
                    leaves=(
                        Leaf(
                            code="03.2.2.0",
                            label="Cleaning, repair and hire of footwear",
                            excludes=(
                                ExcludeRef(
                                    code="03.2.1",
                                    label="parts of footwear, such as heels, soles, etc., purchased by households with the intention of undertaking footwear repair themselves",
                                ),
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="polishes, creams and other shoe-cleaning articles",
                                ),
                                ExcludeRef(
                                    code="09.4.4.0",
                                    label="hire and repair of game-specific footwear (ski boots, football boots, golfing shoes and other such footwear fitted with ice skates, rollers, spikes, studs, etc.)",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
