"""COICOP class 04 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="04",
    label="Housing, water, electricity, gas and other fuels",
    groups=(
        Group(
            code="04.1",
            label="Actual rental payments made for housing",
            subgroups=(
                Subgroup(
                    code="04.1.1",
                    label="Actual rental payments made by tenants for main residence",
                    leaves=(
                        Leaf(
                            code="04.1.1.0",
                            label="Actual rental payments made by tenants for main residence",
                            excludes=(
                                ExcludeRef(
                                    code="04.1.2.2",
                                    label="rental paid for use of a garage that provides parking and storage but not in connection with a dwelling",
                                ),
                                ExcludeRef(
                                    code="11.2.0.3",
                                    label="accommodation services of boarding schools, universities and other educational establishments",
                                ),
                                ExcludeRef(
                                    code="11.2.0.9",
                                    label="accommodation services of hostels for workers",
                                ),
                                ExcludeRef(
                                    code="13.3.0.2",
                                    label="retirement homes for elderly persons",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.1.2",
                    label="Other actual rental payments",
                    leaves=(
                        Leaf(
                            code="04.1.2.1",
                            label="Actual rental payments made by tenants for secondary residences",
                            excludes=(
                                ExcludeRef(
                                    code="11.2.0.2",
                                    label="accommodation services of holiday villages and holiday centres",
                                ),
                            ),
                        ),
                        Leaf(
                            code="04.1.2.2",
                            label="Garage rental payments and other rental payments made by tenants",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.4.1",
                                    label="payment for the use of a parking space or a garage that provides parking but not in connection with a dwelling",
                                ),
                                ExcludeRef(
                                    code="07.4.9.1",
                                    label="removal and storage services",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="04.2",
            label="Imputed rental payments for housing",
            subgroups=(
                Subgroup(
                    code="04.2.1",
                    label="Imputed rental payments of owner-occupiers for their main residence",
                    leaves=(
                        Leaf(
                            code="04.2.1.0",
                            label="Imputed rental payments of owner-occupiers for their main residence",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.2.2",
                    label="Other imputed rentals",
                    leaves=(
                        Leaf(
                            code="04.2.2.0",
                            label="Other imputed rentals",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="04.3",
            label="Maintenance, repair and security of the dwelling",
            subgroups=(
                Subgroup(
                    code="04.3.1",
                    label="Security equipment and materials for dwelling maintenance and repair",
                    leaves=(
                        Leaf(
                            code="04.3.1.1",
                            label="Materials for the maintenance and repair of the dwelling",
                            excludes=(
                                ExcludeRef(code="05.5.2.1", label="hand tools"),
                                ExcludeRef(code="05.5.2.2", label="lamp bulbs"),
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="brooms, scrubbing brushes, dusting brushes and cleaning products",
                                ),
                            ),
                        ),
                        Leaf(
                            code="04.3.1.2",
                            label="Security equipment",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.1.3",
                                    label="fire extinguishers for transport equipment",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.3.2",
                    label="Services for the maintenance, repair and security of the dwelling",
                    leaves=(
                        Leaf(
                            code="04.3.2.0",
                            label="Services for the maintenance, repair and security of the dwelling",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.1.1",
                                    label="separate purchases of materials by households with the intention of undertaking maintenance or repair themselves",
                                ),
                                ExcludeRef(
                                    code="07.2.3.0", label="locksmith services for cars"
                                ),
                                ExcludeRef(code="13.9.0.9", label="bodyguards"),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="04.4",
            label="Water supply and miscellaneous services relating to the dwelling",
            subgroups=(
                Subgroup(
                    code="04.4.1",
                    label="Water supply",
                    leaves=(
                        Leaf(
                            code="04.4.1.1",
                            label="Water supply delivered through network systems",
                            excludes=(
                                ExcludeRef(
                                    code="01.2.5.0",
                                    label="drinking water sold in bottles or containers",
                                ),
                                ExcludeRef(
                                    code="04.5.5.0",
                                    label="hot water and steam purchased from district heating plants",
                                ),
                            ),
                        ),
                        Leaf(
                            code="04.4.1.2",
                            label="Water supply delivered through other systems",
                            excludes=(
                                ExcludeRef(
                                    code="01.2.5.0",
                                    label="drinking water sold in bottles or containers",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.4.2",
                    label="Refuse collection",
                    leaves=(
                        Leaf(
                            code="04.4.2.0",
                            label="Refuse collection",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.4.3",
                    label="Sewage collection",
                    leaves=(
                        Leaf(
                            code="04.4.3.1",
                            label="Sewage collection through sewer systems",
                            excludes=(),
                        ),
                        Leaf(
                            code="04.4.3.2",
                            label="Sewage collection through on-site sanitation systems",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.4.4",
                    label="Other services related to the dwelling",
                    leaves=(
                        Leaf(
                            code="04.4.4.1",
                            label="Charges for maintenance of multi-occupied buildings",
                            excludes=(
                                ExcludeRef(
                                    code="05.6.2.9",
                                    label="household services, such as window cleaning, disinfection, fumigation and pest extermination",
                                ),
                            ),
                        ),
                        Leaf(
                            code="04.4.4.9",
                            label="Other services related to the dwelling n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="04.5",
            label="Electricity, gas and other fuels",
            subgroups=(
                Subgroup(
                    code="04.5.1",
                    label="Electricity",
                    leaves=(
                        Leaf(
                            code="04.5.1.0",
                            label="Electricity",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.5.2",
                    label="Gas",
                    leaves=(
                        Leaf(
                            code="04.5.2.1",
                            label="Natural gas through networks",
                            excludes=(),
                        ),
                        Leaf(
                            code="04.5.2.2",
                            label="Liquefied hydrocarbons",
                            excludes=(
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="fees for delivery of liquefied hydrocarbons (butane, propane, etc.), if separately priced",
                                ),
                                ExcludeRef(
                                    code="09.2.2.2", label="camping gas in cylinders"
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.5.3",
                    label="Liquid fuels",
                    leaves=(
                        Leaf(
                            code="04.5.3.0",
                            label="Liquid fuels",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.5.4",
                    label="Solid fuels",
                    leaves=(
                        Leaf(
                            code="04.5.4.1",
                            label="Coal, coal briquettes, peat and peat briquettes",
                            excludes=(),
                        ),
                        Leaf(
                            code="04.5.4.2",
                            label="Wood fuel, including pellets and briquettes",
                            excludes=(),
                        ),
                        Leaf(
                            code="04.5.4.3",
                            label="Charcoal",
                            excludes=(),
                        ),
                        Leaf(
                            code="04.5.4.9",
                            label="Other solid fuels",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="04.5.5",
                    label="Other energy for heating and cooling",
                    leaves=(
                        Leaf(
                            code="04.5.5.0",
                            label="Other energy for heating and cooling",
                            excludes=(ExcludeRef(code="01.1.8.6", label="ice cubes"),),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
