"""COICOP class 05 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="05",
    label="Furnishings, household equipment and routine household maintenance",
    groups=(
        Group(
            code="05.1",
            label="Furniture, furnishings, and loose carpets",
            subgroups=(
                Subgroup(
                    code="05.1.1",
                    label="Furniture, furnishings and loose carpets",
                    leaves=(
                        Leaf(
                            code="05.1.1.1",
                            label="Household furniture",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="repair, installation and hire of household furniture",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.1.1.2",
                            label="Garden and camping furniture",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="repair, installation and hire of garden and camping furniture",
                                ),
                                ExcludeRef(code="09.2.2.2", label="camping equipment"),
                                ExcludeRef(
                                    code="09.3.1.1", label="decorative garden materials"
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.1.1.3",
                            label="Lighting equipment",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="repair and hire of lighting equipment",
                                ),
                                ExcludeRef(
                                    code="05.5.2.2", label="light bulbs, tubes and LEDs"
                                ),
                                ExcludeRef(
                                    code="09.2.1.3",
                                    label="light strings for Christmas trees",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.1.1.4",
                            label="Furnishings, loose carpets and rugs",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.1.1", label="fitted carpets and linoleum"
                                ),
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="installation of furniture and furnishings if separately priced from delivery",
                                ),
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="repair and hire of loose carpets and other furniture and furnishings",
                                ),
                                ExcludeRef(
                                    code="05.2.1.2", label="bedding (bed linen)"
                                ),
                                ExcludeRef(code="05.2.1.9", label="sunshades"),
                                ExcludeRef(code="05.3.1.9", label="safes"),
                                ExcludeRef(
                                    code="05.4.0.1",
                                    label="ornamental glass and ceramic articles",
                                ),
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="delivery of loose carpets and other furniture and furnishings if separately priced",
                                ),
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="installation of furniture and furnishings if not separately priced from delivery",
                                ),
                                ExcludeRef(
                                    code="13.2.9.1",
                                    label="carrycots, pushchairs and strollers; and wall thermometers and barometers",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.1.2",
                    label="Repair, installation and hire of furniture, furnishings and loose carpets",
                    leaves=(
                        Leaf(
                            code="05.1.2.0",
                            label="Repair, installation and hire of furniture, furnishings and loose carpets",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.2.0",
                                    label="laying and repair of fitted carpets, linoleum and other such floor coverings",
                                ),
                                ExcludeRef(
                                    code="05.1.1",
                                    label="materials purchased by households with the intention of undertaking maintenance and repair themselves",
                                ),
                                ExcludeRef(
                                    code="05.6.2.9",
                                    label="dry-cleaning and shampooing of carpets",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="05.2",
            label="Household textiles",
            subgroups=(
                Subgroup(
                    code="05.2.1",
                    label="Household textiles",
                    leaves=(
                        Leaf(
                            code="05.2.1.1",
                            label="Furnishing fabrics and curtains",
                            excludes=(
                                ExcludeRef(
                                    code="05.2.2.0",
                                    label="repair and sewing of curtains",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.2.1.2",
                            label="Bed linen and bedding",
                            excludes=(
                                ExcludeRef(
                                    code="05.2.2.0",
                                    label="repair and sewing of bed linen",
                                ),
                                ExcludeRef(code="05.3.2.9", label="electric blankets"),
                                ExcludeRef(
                                    code="09.2.2.2",
                                    label="air mattresses and sleeping bags",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.2.1.3",
                            label="Table linen and bathroom linen",
                            excludes=(
                                ExcludeRef(
                                    code="05.2.2.0",
                                    label="repair and sewing of table and bathroom linen",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.2.1.9",
                            label="Other household textiles",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.1.1", label="fabric wall coverings"
                                ),
                                ExcludeRef(
                                    code="05.1.1.4",
                                    label="floor coverings, such as loose carpets and rugs; and tapestries",
                                ),
                                ExcludeRef(
                                    code="05.2.2.0",
                                    label="repair and sewing of other household textiles",
                                ),
                                ExcludeRef(
                                    code="07.2.1.3",
                                    label="covers for motor cars, motorcycles, etc.",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.2.2",
                    label="Repair, hire and sewing services of household textiles",
                    leaves=(
                        Leaf(
                            code="05.2.2.0",
                            label="Repair, hire and sewing services of household textiles",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="05.3",
            label="Household appliances",
            subgroups=(
                Subgroup(
                    code="05.3.1",
                    label="Major electric and other household appliances",
                    leaves=(
                        Leaf(
                            code="05.3.1.1",
                            label="Major kitchen appliances",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of kitchen appliances",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.1.2",
                            label="Major laundry appliances",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of laundry appliances",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.1.3",
                            label="Heaters and air conditioners",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of these appliances",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.1.4",
                            label="Cleaning equipment",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of cleaning equipment",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.1.9",
                            label="Other major household appliances",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair and hire of household appliances",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.3.2",
                    label="Small household appliances",
                    leaves=(
                        Leaf(
                            code="05.3.2.1",
                            label="Small appliances for the cooking and processing of food",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of food processing appliances",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.2.2",
                            label="Small appliances for the preparation of beverages",
                            excludes=(
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of coffee machines, tea makers and similar appliances",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.3.2.9",
                            label="Other small household appliances",
                            excludes=(
                                ExcludeRef(code="05.3.1.2", label="ironing machines"),
                                ExcludeRef(
                                    code="05.3.3.0",
                                    label="repair, installation and hire of other small household appliances",
                                ),
                                ExcludeRef(
                                    code="05.4.0.3",
                                    label="small non-electric household articles and kitchen utensils",
                                ),
                                ExcludeRef(code="06.1.2.1", label="baby scales"),
                                ExcludeRef(
                                    code="13.1.2.0", label="personal weighing machines"
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.3.3",
                    label="Repair, installation and hire of household appliances",
                    leaves=(
                        Leaf(
                            code="05.3.3.0",
                            label="Repair, installation and hire of household appliances",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="05.4",
            label="Glassware, tableware and household utensils",
            subgroups=(
                Subgroup(
                    code="05.4.0",
                    label="Glassware, tableware and household utensils",
                    leaves=(
                        Leaf(
                            code="05.4.0.1",
                            label="Glassware, crystal ware, ceramic ware and china ware",
                            excludes=(
                                ExcludeRef(
                                    code="05.4.0.4",
                                    label="repair and hire of glassware, crystal ware, ceramic ware and chinaware",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.4.0.2",
                            label="Cutlery, flatware and silverware",
                            excludes=(
                                ExcludeRef(
                                    code="05.4.0.4",
                                    label="repair and hire of cutlery, flatware and silverware",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.4.0.3",
                            label="Kitchen utensils and articles",
                            excludes=(
                                ExcludeRef(
                                    code="05.4.0.4",
                                    label="repair and hire of kitchen utensils and articles",
                                ),
                                ExcludeRef(
                                    code="05.6.1.9", label="disposable tableware"
                                ),
                                ExcludeRef(code="13.2.9.1", label="ashtrays"),
                            ),
                        ),
                        Leaf(
                            code="05.4.0.4",
                            label="Repair and hire of glassware, tableware and household utensils",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="05.5",
            label="Tools and equipment for house and garden",
            subgroups=(
                Subgroup(
                    code="05.5.1",
                    label="Motorized tools and equipment",
                    leaves=(
                        Leaf(
                            code="05.5.1.0",
                            label="Motorized tools and equipment",
                            excludes=(
                                ExcludeRef(
                                    code="05.5.3.0",
                                    label="repair, installation and hire of motorized major tools and equipment",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.5.2",
                    label="Non-motorized tools and miscellaneous accessories",
                    leaves=(
                        Leaf(
                            code="05.5.2.1",
                            label="Non-motorized tools",
                            excludes=(
                                ExcludeRef(
                                    code="05.5.3.0",
                                    label="repair and hire of non-motorized small tools",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.5.2.2",
                            label="Miscellaneous accessories",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.1.1",
                                    label="door fittings, power sockets, switches and wiring flex",
                                ),
                                ExcludeRef(
                                    code="05.5.3.0",
                                    label="repair and hire of miscellaneous small tool accessories",
                                ),
                                ExcludeRef(
                                    code="07.2.1.2",
                                    label="fuses for cars, motorcycles, etc.",
                                ),
                                ExcludeRef(
                                    code="08.1.9.2",
                                    label="batteries for information and communication equipment",
                                ),
                                ExcludeRef(
                                    code="09.1.1.2",
                                    label="batteries for photographic and cinematographic equipment",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.5.3",
                    label="Repair and hire of motorized and non-motorized tools and equipment",
                    leaves=(
                        Leaf(
                            code="05.5.3.0",
                            label="Repair and hire of motorized and non-motorized tools and equipment",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="05.6",
            label="Goods and services for routine household maintenance",
            subgroups=(
                Subgroup(
                    code="05.6.1",
                    label="Non-durable household goods",
                    leaves=(
                        Leaf(
                            code="05.6.1.1",
                            label="Household cleaning and maintenance products",
                            excludes=(
                                ExcludeRef(
                                    code="04.3.1.1",
                                    label="brushes and scrapers for paint, varnish and wallpaper",
                                ),
                                ExcludeRef(
                                    code="07.2.1.3",
                                    label="products used specifically for the cleaning and maintenance of transport equipment, such as paints, chrome cleaners, sealing compounds and bodywork polishes",
                                ),
                                ExcludeRef(
                                    code="09.3.1.1",
                                    label="horticultural products for the upkeep of ornamental gardens",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.6.1.9",
                            label="Other non-durable household goods",
                            excludes=(
                                ExcludeRef(
                                    code="13.1.2.0",
                                    label="paper handkerchiefs, toilet paper, toilet soaps, toilet sponges and other personal hygiene products",
                                ),
                                ExcludeRef(
                                    code="13.2.9.1",
                                    label="cigarette, cigar and pipe lighters and lighter fuel",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="05.6.2",
                    label="Domestic services and household services",
                    leaves=(
                        Leaf(
                            code="05.6.2.1",
                            label="Domestic services provided by paid staff",
                            excludes=(
                                ExcludeRef(
                                    code="10.1.0.1",
                                    label="child-minding with an educational component",
                                ),
                                ExcludeRef(
                                    code="13.3.0.1",
                                    label="child-minding outside the home",
                                ),
                            ),
                        ),
                        Leaf(
                            code="05.6.2.9",
                            label="Other household services",
                            excludes=(
                                ExcludeRef(
                                    code="03.1.4.1",
                                    label="dry-cleaning, laundering and dyeing of garments",
                                ),
                                ExcludeRef(code="04.3.2.0", label="security services"),
                                ExcludeRef(code="04.4.2.0", label="refuse collection"),
                                ExcludeRef(code="04.4.3", label="sewage collection"),
                                ExcludeRef(
                                    code="04.4.4.1",
                                    label="co-proprietor charges for caretaking, gardening, stairwell cleaning, heating and lighting, maintenance of lifts and refuse disposal chutes, etc. in multi-occupied buildings",
                                ),
                                ExcludeRef(
                                    code="04.4.4.9",
                                    label="snow removal and chimney sweeping",
                                ),
                                ExcludeRef(
                                    code="07.4.9.1",
                                    label="removal and storage services",
                                ),
                                ExcludeRef(code="13.9.0.9", label="bodyguards"),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
