"""COICOP class 06 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="06",
    label="Health",
    groups=(
        Group(
            code="06.1",
            label="Medicines and health products",
            subgroups=(
                Subgroup(
                    code="06.1.1",
                    label="Medicines",
                    leaves=(
                        Leaf(
                            code="06.1.1.1",
                            label="Medicines, vaccines and other pharmaceutical preparations",
                            excludes=(
                                ExcludeRef(
                                    code="09.3.2.2", label="veterinary products"
                                ),
                            ),
                        ),
                        Leaf(
                            code="06.1.1.2",
                            label="Herbal medicines and homeopathic products",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.1.2",
                    label="Medical products",
                    leaves=(
                        Leaf(
                            code="06.1.2.1",
                            label="Medical diagnostic products",
                            excludes=(ExcludeRef(code="13.1.2.0", label="scales"),),
                        ),
                        Leaf(
                            code="06.1.2.2",
                            label="Preventive and protective devices",
                            excludes=(
                                ExcludeRef(
                                    code="06.1.1.1", label="oral contraceptives"
                                ),
                            ),
                        ),
                        Leaf(
                            code="06.1.2.3",
                            label="Treatment devices for personal use",
                            excludes=(
                                ExcludeRef(
                                    code="06.1.1.1",
                                    label="inhalators and nebulizers with medication",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.1.3",
                    label="Assistive products",
                    leaves=(
                        Leaf(
                            code="06.1.3.1",
                            label="Assistive products for vision",
                            excludes=(
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="goggles for protection against potential eye damage resulting from the practice of a sport",
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="walking sticks and canes for recreational purposes (e.g., hiking and tracking)",
                                ),
                                ExcludeRef(
                                    code="13.2.9.1",
                                    label="(non-corrective) sunglasses and protective glasses",
                                ),
                            ),
                        ),
                        Leaf(
                            code="06.1.3.2",
                            label="Assistive products for hearing and communication",
                            excludes=(),
                        ),
                        Leaf(
                            code="06.1.3.3",
                            label="Assistive products for mobility and daily living",
                            excludes=(
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="walking sticks and canes for recreational purposes (e.g., hiking and tracking)",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.1.4",
                    label="Repair, rental and maintenance of medical and assistive products",
                    leaves=(
                        Leaf(
                            code="06.1.4.0",
                            label="Repair, rental and maintenance of medical and assistive products",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="06.2",
            label="Outpatient care services",
            subgroups=(
                Subgroup(
                    code="06.2.1",
                    label="Preventive care services",
                    leaves=(
                        Leaf(
                            code="06.2.1.1",
                            label="Immunization services",
                            excludes=(
                                ExcludeRef(
                                    code="06.1.1.1",
                                    label="the vaccine itself when priced separately from the service",
                                ),
                            ),
                        ),
                        Leaf(
                            code="06.2.1.9",
                            label="Other preventive care services",
                            excludes=(
                                ExcludeRef(
                                    code="06.2.2.1",
                                    label="routine dental preventive check-ups",
                                ),
                                ExcludeRef(
                                    code="06.3",
                                    label="control and follow-up services for the treatment of symptoms that arise during the provision of overnight care",
                                ),
                                ExcludeRef(
                                    code="06.4",
                                    label="laboratory and imaging services priced separately from preventive care services",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.2.2",
                    label="Outpatient dental services",
                    leaves=(
                        Leaf(
                            code="06.2.2.1",
                            label="Dental preventive services",
                            excludes=(),
                        ),
                        Leaf(
                            code="06.2.2.9",
                            label="Other outpatient dental services",
                            excludes=(
                                ExcludeRef(
                                    code="06.1",
                                    label="all health products (e.g., assistive, medical, pharmaceutical and therapeutic) needed to deliver outpatient dental services that are priced separately from the provider’s services",
                                ),
                                ExcludeRef(
                                    code="06.4.1.0",
                                    label="services of medical laboratories performing analytic testing and diagnostic imaging centres priced separately from dental services received",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.2.3",
                    label="Other outpatient care services",
                    leaves=(
                        Leaf(
                            code="06.2.3.1",
                            label="Outpatient curative and rehabilitative services",
                            excludes=(
                                ExcludeRef(
                                    code="06.1",
                                    label="medicines and health products (medical, assistive) priced separately from the services of the provider (e.g., specialist, physician, nurse or another type of health-care practitioner)",
                                ),
                                ExcludeRef(
                                    code="06.2.1", label="preventive care services"
                                ),
                                ExcludeRef(
                                    code="06.2.2", label="outpatient dental services"
                                ),
                                ExcludeRef(
                                    code="06.4.1.0",
                                    label="diagnostic imaging services and medical laboratory services priced separately from the services of the provider (specialist, physician, nurse or another type of health-care practitioner)",
                                ),
                                ExcludeRef(
                                    code="06.4.2.0",
                                    label="patient emergency transportation services and emergency rescue",
                                ),
                            ),
                        ),
                        Leaf(
                            code="06.2.3.2",
                            label="Outpatient long-term care services",
                            excludes=(
                                ExcludeRef(
                                    code="06.1",
                                    label="medicines and health products (medical, assistive) priced separately from the service of the provider (specialist, physician, nurse or another type of health-care practitioner)",
                                ),
                                ExcludeRef(
                                    code="06.4.1.0",
                                    label="diagnostic imaging services and medical laboratory services priced separately from the service fee of the provider (specialist, physician, nurse or another type of health-care practitioner)",
                                ),
                                ExcludeRef(
                                    code="06.4.2.0",
                                    label="patient emergency transportation services and emergency rescue",
                                ),
                                ExcludeRef(
                                    code="13.3.0.3",
                                    label="social assistance services including care delivered to enable a person to live independently in a house or an apartment; community and leisure activities; and occupational support provided on a continuing or recurrent basis",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="06.3",
            label="Inpatient care services",
            subgroups=(
                Subgroup(
                    code="06.3.1",
                    label="Inpatient curative and rehabilitative services",
                    leaves=(
                        Leaf(
                            code="06.3.1.0",
                            label="Inpatient curative and rehabilitative services",
                            excludes=(
                                ExcludeRef(
                                    code="06.2",
                                    label="hospital day care (with or without admission and without an overnight stay) and home-based hospital treatment",
                                ),
                                ExcludeRef(
                                    code="06.2",
                                    label="services provided in a hospital or a hospital setting without an overnight stay (06.2), including services provided by facilities, such as surgeries, clinics and dispensaries, devoted exclusively to outpatient care",
                                ),
                                ExcludeRef(
                                    code="06.4.2.0",
                                    label="patient emergency transportation services and emergency rescue",
                                ),
                                ExcludeRef(
                                    code="13.3.0.2",
                                    label="services provided by non-medical retirement homes for elderly persons, non-medical institutions for disabled persons, non-medical rehabilitation centres offering primarily long-term social support and retirement villages that do not offer inpatient medical services",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.3.2",
                    label="Inpatient long-term care services",
                    leaves=(
                        Leaf(
                            code="06.3.2.0",
                            label="Inpatient long-term care services",
                            excludes=(
                                ExcludeRef(
                                    code="13.3", label="social protection services"
                                ),
                                ExcludeRef(
                                    code="13.3.0.2",
                                    label="non-medical retirement homes for elderly persons and non-medical residences for disabled persons",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="06.4",
            label="Other health services",
            subgroups=(
                Subgroup(
                    code="06.4.1",
                    label="Diagnostic imaging services and medical laboratory services",
                    leaves=(
                        Leaf(
                            code="06.4.1.0",
                            label="Diagnostic imaging services and medical laboratory services",
                            excludes=(
                                ExcludeRef(
                                    code="06.2.1",
                                    label="diagnostic imaging services and medical laboratory services not priced separately from outpatient preventive care services",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="06.4.2",
                    label="Patient emergency transportation and emergency rescue services",
                    leaves=(
                        Leaf(
                            code="06.4.2.0",
                            label="Patient emergency transportation and emergency rescue services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
