"""COICOP class 07 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="07",
    label="Transport",
    groups=(
        Group(
            code="07.1",
            label="Purchase of vehicles",
            subgroups=(
                Subgroup(
                    code="07.1.1",
                    label="Motor cars",
                    leaves=(
                        Leaf(
                            code="07.1.1.1",
                            label="New motor cars",
                            excludes=(
                                ExcludeRef(code="06.1.3.3", label="invalid carriages"),
                                ExcludeRef(code="09.1.2.1", label="camper vans"),
                                ExcludeRef(code="09.1.2.9", label="golf carts"),
                            ),
                        ),
                        Leaf(
                            code="07.1.1.2",
                            label="Second-hand motor cars",
                            excludes=(
                                ExcludeRef(code="06.1.3.3", label="invalid carriages"),
                                ExcludeRef(code="09.1.2.1", label="camper vans"),
                                ExcludeRef(code="09.1.2.9", label="golf carts"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.1.2",
                    label="Motorcycles",
                    leaves=(
                        Leaf(
                            code="07.1.2.0",
                            label="Motorcycles",
                            excludes=(
                                ExcludeRef(
                                    code="07.1.3.0",
                                    label="electric bicycles (e-bikes), pedelecs",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.1.3",
                    label="Bicycles",
                    leaves=(
                        Leaf(
                            code="07.1.3.0",
                            label="Bicycles",
                            excludes=(
                                ExcludeRef(
                                    code="07.1.2.0",
                                    label="motorized bicycles with combustion engines",
                                ),
                                ExcludeRef(
                                    code="09.2.1.2",
                                    label="toy bicycles and toy tricycles",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.1.4",
                    label="Animal-drawn vehicles",
                    leaves=(
                        Leaf(
                            code="07.1.4.0",
                            label="Animal-drawn vehicles",
                            excludes=(
                                ExcludeRef(
                                    code="09.1.2.4",
                                    label="horses and ponies and horse- and pony-drawn vehicles purchased for recreational purposes and related equipment",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="07.2",
            label="Operation of personal transport equipment",
            subgroups=(
                Subgroup(
                    code="07.2.1",
                    label="Parts and accessories for personal transport equipment",
                    leaves=(
                        Leaf(
                            code="07.2.1.1",
                            label="Tyres",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.2.1.2",
                            label="Parts for personal transport equipment",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.3.0",
                                    label="services purchased for the fitting of parts and accessories and for the painting, washing and polishing of bodywork",
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.2.1.3",
                            label="Accessories for personal transport equipment",
                            excludes=(
                                ExcludeRef(
                                    code="05.6.1.1",
                                    label="non-specific products used for cleaning and maintenance, such as household sponges, chamois leathers and detergents",
                                ),
                                ExcludeRef(
                                    code="08.1.4.0",
                                    label="audio and video systems for cars",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.2.2",
                    label="Fuels and lubricants for personal transport equipment",
                    leaves=(
                        Leaf(
                            code="07.2.2.1",
                            label="Diesel",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.2.2.2",
                            label="Petrol",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.2.3", label="two-stroke mixtures"
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.2.2.3",
                            label="Other fuels for personal transport equipment",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.2.2.4",
                            label="Lubricants",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.3.0",
                                    label="services purchased for oil changes and greasing",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.2.3",
                    label="Maintenance and repair of personal transport equipment",
                    leaves=(
                        Leaf(
                            code="07.2.3.0",
                            label="Maintenance and repair of personal transport equipment",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.4.3", label="roadworthiness tests"
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.2.4",
                    label="Other services related to personal transport equipment",
                    leaves=(
                        Leaf(
                            code="07.2.4.1",
                            label="Parking services",
                            excludes=(
                                ExcludeRef(
                                    code="04.1.2.2",
                                    label="rental of a parking space or a garage that provides parking in connection with a dwelling",
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.2.4.2",
                            label="Toll facilities",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.2.4.3",
                            label="Driving lessons, tests, licences and roadworthiness tests",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.2.4.4",
                            label="Hire of personal transport equipment without driver",
                            excludes=(
                                ExcludeRef(
                                    code="07.3.2.2",
                                    label="passenger transport services by taxi and hired vehicle with driver",
                                ),
                                ExcludeRef(
                                    code="09.4.2.2",
                                    label="rental of personal transport equipment for recreation",
                                ),
                                ExcludeRef(
                                    code="12.1.4.1",
                                    label="service charges for personal transport equipment insurance",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="07.3",
            label="Passenger transport services",
            subgroups=(
                Subgroup(
                    code="07.3.1",
                    label="Passenger transport by railway",
                    leaves=(
                        Leaf(
                            code="07.3.1.1",
                            label="Passenger transport by train",
                            excludes=(
                                ExcludeRef(
                                    code="07.3.6.0", label="funicular transport"
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.3.1.2",
                            label="Passenger transport by rapid transit and tram",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.3.2",
                    label="Passenger transport by road",
                    leaves=(
                        Leaf(
                            code="07.3.2.1",
                            label="Passenger transport by bus and coach",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.3.2.2",
                            label="Passenger transport by taxi and hired vehicle with driver",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.3.2.3",
                            label="Passenger transport for students to and from school",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.3.2.9",
                            label="Other passenger transport by road",
                            excludes=(
                                ExcludeRef(
                                    code="07.3.2.1",
                                    label="transport of persons and accompanied luggage by busses with driver",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.3.3",
                    label="Passenger transport by air",
                    leaves=(
                        Leaf(
                            code="07.3.3.1",
                            label="Passenger transport by air, domestic",
                            excludes=(),
                        ),
                        Leaf(
                            code="07.3.3.2",
                            label="Passenger transport by air, international",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.3.4",
                    label="Passenger transport by sea and inland waterway",
                    leaves=(
                        Leaf(
                            code="07.3.4.0",
                            label="Passenger transport by sea and inland waterway",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.3.5",
                    label="Combined passenger transport",
                    leaves=(
                        Leaf(
                            code="07.3.5.0",
                            label="Combined passenger transport",
                            excludes=(
                                ExcludeRef(code="09.8.0.0", label="package holidays"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.3.6",
                    label="Other passenger transport services",
                    leaves=(
                        Leaf(
                            code="07.3.6.0",
                            label="Other passenger transport services",
                            excludes=(
                                ExcludeRef(
                                    code="09.4.6.2",
                                    label="cable-car and chairlift transport at ski resorts and holiday centres",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="07.4",
            label="Transport services for goods",
            subgroups=(
                Subgroup(
                    code="07.4.1",
                    label="Postal and courier services",
                    leaves=(
                        Leaf(
                            code="07.4.1.1",
                            label="Letter handling services",
                            excludes=(
                                ExcludeRef(
                                    code="09.7.4.0",
                                    label="postcards, envelopes and other postal matter, not pre-franked",
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.4.1.2",
                            label="Courier and parcel delivery services",
                            excludes=(
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="delivery services for goods (e.g., furniture and groceries), if separately priced",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="07.4.9",
                    label="Other transport of goods",
                    leaves=(
                        Leaf(
                            code="07.4.9.1",
                            label="Removal and storage services",
                            excludes=(
                                ExcludeRef(code="04.1.2.2", label="self-storage units"),
                                ExcludeRef(
                                    code="07.3.6.0",
                                    label="services of porters and left-luggage and luggage-forwarding offices",
                                ),
                            ),
                        ),
                        Leaf(
                            code="07.4.9.2",
                            label="Delivery of goods",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
