"""COICOP class 08 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="08",
    label="Information and communication",
    groups=(
        Group(
            code="08.1",
            label="Information and communication equipment",
            subgroups=(
                Subgroup(
                    code="08.1.1",
                    label="Fixed telephone equipment",
                    leaves=(
                        Leaf(
                            code="08.1.1.0",
                            label="Fixed telephone equipment",
                            excludes=(
                                ExcludeRef(
                                    code="08.1.3.1",
                                    label="telefax and telephone-answering facilities provided by personal computers",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.1.2",
                    label="Mobile telephone equipment",
                    leaves=(
                        Leaf(
                            code="08.1.2.0",
                            label="Mobile telephone equipment",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.1.3",
                    label="Information processing equipment",
                    leaves=(
                        Leaf(
                            code="08.1.3.1",
                            label="Computers, laptops and tablets",
                            excludes=(
                                ExcludeRef(
                                    code="08.2.0.0",
                                    label="computer software packages, comprising, for example, operating systems, applications and programming languages",
                                ),
                                ExcludeRef(
                                    code="09.2.1.1",
                                    label="video game software; and video game computers and consoles",
                                ),
                                ExcludeRef(
                                    code="09.7.1.1",
                                    label="books, dictionaries, encyclopaedias, foreign language trainers, multimedia presentations, etc. in the form of software",
                                ),
                            ),
                        ),
                        Leaf(
                            code="08.1.3.2",
                            label="Peripheral equipment and its consumable components",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.1.4",
                    label="Equipment for the reception, recording and reproduction of sound and vision",
                    leaves=(
                        Leaf(
                            code="08.1.4.0",
                            label="Equipment for the reception, recording and reproduction of sound and vision",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.1.5",
                    label="Unrecorded recording media",
                    leaves=(
                        Leaf(
                            code="08.1.5.0",
                            label="Unrecorded recording media",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.1.9",
                    label="Other information and communication equipment and accessories",
                    leaves=(
                        Leaf(
                            code="08.1.9.1",
                            label="Other information and communication equipment",
                            excludes=(),
                        ),
                        Leaf(
                            code="08.1.9.2",
                            label="Other information and communication accessories",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="08.2",
            label="Software, excluding games",
            subgroups=(
                Subgroup(
                    code="08.2.0",
                    label="Software, excluding games",
                    leaves=(
                        Leaf(
                            code="08.2.0.0",
                            label="Software, excluding games",
                            excludes=(
                                ExcludeRef(
                                    code="09.2.1.1", label="video game software"
                                ),
                                ExcludeRef(
                                    code="09.7.1.1",
                                    label="books, dictionaries, encyclopaedias, foreign language trainers, multimedia presentations, etc. in the form of software",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="08.3",
            label="Information and communication services",
            subgroups=(
                Subgroup(
                    code="08.3.1",
                    label="Fixed communication services",
                    leaves=(
                        Leaf(
                            code="08.3.1.0",
                            label="Fixed communication services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.3.2",
                    label="Mobile communication services",
                    leaves=(
                        Leaf(
                            code="08.3.2.0",
                            label="Mobile communication services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.3.3",
                    label="Internet access provision services and online storage services",
                    leaves=(
                        Leaf(
                            code="08.3.3.0",
                            label="Internet access provision services and online storage services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.3.4",
                    label="Bundled telecommunication services",
                    leaves=(
                        Leaf(
                            code="08.3.4.0",
                            label="Bundled telecommunication services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.3.5",
                    label="Repair and rental of information and communication equipment",
                    leaves=(
                        Leaf(
                            code="08.3.5.0",
                            label="Repair and rental of information and communication equipment",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="08.3.9",
                    label="Other information and communication services",
                    leaves=(
                        Leaf(
                            code="08.3.9.1",
                            label="Television and radio licences and fees",
                            excludes=(),
                        ),
                        Leaf(
                            code="08.3.9.2",
                            label="Subscriptions to audiovisual streaming services and rental of audiovisual content",
                            excludes=(
                                ExcludeRef(
                                    code="09.4.3.1",
                                    label="rental of and subscription to video game software and online games",
                                ),
                                ExcludeRef(
                                    code="09.5.2.0",
                                    label="audiovisual content purchased online for immediate download",
                                ),
                            ),
                        ),
                        Leaf(
                            code="08.3.9.9",
                            label="Other information and communication services n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
