"""COICOP class 09 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="09",
    label="Recreation, sport and culture",
    groups=(
        Group(
            code="09.1",
            label="Recreational durables",
            subgroups=(
                Subgroup(
                    code="09.1.1",
                    label="Photographic and cinematographic equipment and optical instruments",
                    leaves=(
                        Leaf(
                            code="09.1.1.1",
                            label="Cameras",
                            excludes=(
                                ExcludeRef(code="07.2.1.3", label="dash cameras"),
                                ExcludeRef(code="08.1.3.2", label="web cameras"),
                            ),
                        ),
                        Leaf(
                            code="09.1.1.2",
                            label="Accessories for photographic and cinematographic equipment",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.1.1.3",
                            label="Optical instruments",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.1.2",
                    label="Major recreational durables",
                    leaves=(
                        Leaf(
                            code="09.1.2.1",
                            label="Camper vans, caravans and trailers",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.1.2.2",
                            label="Aeroplanes, microlight aircraft, gliders, hang gliders and hot-air balloons",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.1.2.3",
                            label="Boats, yachts, outboard motors and other water-sport equipment",
                            excludes=(
                                ExcludeRef(
                                    code="09.2.2.2",
                                    label="inflatable boats, rafts and swimming pools",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.1.2.4",
                            label="Horses, ponies, camels and dromedaries and accessories",
                            excludes=(
                                ExcludeRef(
                                    code="07.1.4.0",
                                    label="horses and ponies, horse- and pony-drawn vehicles, camels and dromedaries, and related equipment, purchased for personal transport",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.1.2.9",
                            label="Other major recreational durables",
                            excludes=(
                                ExcludeRef(
                                    code="07.1.3.0", label="electric kick scooters"
                                ),
                                ExcludeRef(
                                    code="09.2.2.2",
                                    label="inflatable boats, rafts and swimming pools",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.2",
            label="Other recreational goods",
            subgroups=(
                Subgroup(
                    code="09.2.1",
                    label="Games, toys and hobby-related articles",
                    leaves=(
                        Leaf(
                            code="09.2.1.1",
                            label="Video game computers, consoles, game applications and software",
                            excludes=(
                                ExcludeRef(
                                    code="09.4.3.1",
                                    label="video game subscriptions and rentals",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.2.1.2",
                            label="Other games, toys and hobby-related articles",
                            excludes=(
                                ExcludeRef(
                                    code="09.7.1.9", label="children’s scrapbooks"
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.2.1.3",
                            label="Celebration articles",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.2.2",
                    label="Sporting, camping and open-air recreation equipment",
                    leaves=(
                        Leaf(
                            code="09.2.2.1",
                            label="Sporting equipment",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.1.3",
                                    label="motorcycle and bicycle crash helmets",
                                ),
                                ExcludeRef(
                                    code="09.4.4.0",
                                    label="rental and repair of sporting, camping and open-air recreation equipment",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.2.2.2",
                            label="Camping and open-air recreation equipment",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.1.2",
                                    label="garden and camping furniture",
                                ),
                                ExcludeRef(
                                    code="09.4.4.0",
                                    label="rental and repair of camping and open-air recreation equipment",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.3",
            label="Garden products and pets",
            subgroups=(
                Subgroup(
                    code="09.3.1",
                    label="Garden products, plants and flowers",
                    leaves=(
                        Leaf(
                            code="09.3.1.1",
                            label="Garden products",
                            excludes=(
                                ExcludeRef(
                                    code="05.5.1.0",
                                    label="motorized gardening equipment",
                                ),
                                ExcludeRef(
                                    code="05.5.2.1",
                                    label="non-motorized gardening tools",
                                ),
                                ExcludeRef(
                                    code="05.6.1.9",
                                    label="insecticides, pesticides and fungicides for household use; gardening gloves",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.3.1.2",
                            label="Plants, seeds and flowers",
                            excludes=(
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="flower and plant delivery charges, if separately priced",
                                ),
                                ExcludeRef(code="09.2.1.3", label="Christmas trees"),
                                ExcludeRef(
                                    code="09.3.1.1",
                                    label="soil, peat, composts and fertilizers",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.3.2",
                    label="Pets and pet products",
                    leaves=(
                        Leaf(
                            code="09.3.2.1",
                            label="Pets",
                            excludes=(
                                ExcludeRef(
                                    code="07.1.4.0",
                                    label="horses, ponies, camels and dromedaries used for transport",
                                ),
                                ExcludeRef(
                                    code="09.1.2.4",
                                    label="horses, ponies, camels and dromedaries used for recreation",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.3.2.2",
                            label="Products for pets and other household animals",
                            excludes=(
                                ExcludeRef(
                                    code="09.4.5.0",
                                    label="veterinary and other services for pets and other household animals",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.4",
            label="Recreational services",
            subgroups=(
                Subgroup(
                    code="09.4.1",
                    label="Hire and repair of photographic and cinematographic equipment and optical instruments",
                    leaves=(
                        Leaf(
                            code="09.4.1.0",
                            label="Hire and repair of photographic and cinematographic equipment and optical instruments",
                            excludes=(
                                ExcludeRef(
                                    code="09.1.1",
                                    label="separate purchases of materials made by households with the intention of undertaking maintenance and repair themselves",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.2",
                    label="Hire, maintenance and repair of major recreational durables",
                    leaves=(
                        Leaf(
                            code="09.4.2.1",
                            label="Hire, maintenance and repair of camper vans and caravans",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.2",
                                    label="fuel and lubricants for recreational vehicles",
                                ),
                                ExcludeRef(
                                    code="09.1.2",
                                    label="materials purchased by households with the intention of undertaking maintenance or repair themselves",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.4.2.2",
                            label="Hire, maintenance and repair of other major recreational durables",
                            excludes=(
                                ExcludeRef(
                                    code="07.2.2",
                                    label="fuel and lubricants for recreational vehicles",
                                ),
                                ExcludeRef(
                                    code="07.2.4.4",
                                    label="rental of equipment for transport",
                                ),
                                ExcludeRef(
                                    code="09.1.2",
                                    label="materials purchased by households with the intention of undertaking maintenance or repair themselves",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.3",
                    label="Hire and repair of games, toys and hobby-related articles",
                    leaves=(
                        Leaf(
                            code="09.4.3.1",
                            label="Hire of game software and subscription to online games",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.4.3.2",
                            label="Hire and repair of other games, toys and hobby-related articles",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.4",
                    label="Hire and repair of sporting, camping and open-air recreational equipment",
                    leaves=(
                        Leaf(
                            code="09.4.4.0",
                            label="Hire and repair of sporting, camping and open-air recreational equipment",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.5",
                    label="Veterinary and other services for pets",
                    leaves=(
                        Leaf(
                            code="09.4.5.0",
                            label="Veterinary and other services for pets",
                            excludes=(
                                ExcludeRef(code="09.3.2.2", label="pet products"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.6",
                    label="Recreational and sporting services",
                    leaves=(
                        Leaf(
                            code="09.4.6.1",
                            label="Recreational and leisure services",
                            excludes=(
                                ExcludeRef(code="09.4.7.0", label="games of chance"),
                            ),
                        ),
                        Leaf(
                            code="09.4.6.2",
                            label="Services associated with the practice of sports",
                            excludes=(
                                ExcludeRef(
                                    code="07.3.6.0",
                                    label="cable-car and chairlift transport other than at ski resorts or holiday centres",
                                ),
                            ),
                        ),
                        Leaf(
                            code="09.4.6.3",
                            label="Services associated with attendance at sporting events",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.4.7",
                    label="Games of chance",
                    leaves=(
                        Leaf(
                            code="09.4.7.0",
                            label="Games of chance",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.5",
            label="Cultural goods",
            subgroups=(
                Subgroup(
                    code="09.5.1",
                    label="Musical instruments",
                    leaves=(
                        Leaf(
                            code="09.5.1.0",
                            label="Musical instruments",
                            excludes=(
                                ExcludeRef(code="09.2.1.2", label="toy instruments"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.5.2",
                    label="Audiovisual media",
                    leaves=(
                        Leaf(
                            code="09.5.2.0",
                            label="Audiovisual media",
                            excludes=(
                                ExcludeRef(
                                    code="08.2.0.0",
                                    label="software (other than video game software)",
                                ),
                                ExcludeRef(
                                    code="09.2.1.1",
                                    label="video games and game applications and software",
                                ),
                                ExcludeRef(
                                    code="09.7.1",
                                    label="recorded tapes, CDs, DVDs, Blu-ray discs, gramophone records and flash drives, reproducing books, both educational and non-educational, novels, plays, poetry, dictionaries, encyclopaedias, guidebooks and musical scores",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.6",
            label="Cultural services",
            subgroups=(
                Subgroup(
                    code="09.6.1",
                    label="Services provided by cinemas, theatres and concert venues",
                    leaves=(
                        Leaf(
                            code="09.6.1.0",
                            label="Services provided by cinemas, theatres and concert venues",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.6.2",
                    label="Services provided by museums, libraries and cultural sites",
                    leaves=(
                        Leaf(
                            code="09.6.2.0",
                            label="Services provided by museums, libraries and cultural sites",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.6.3",
                    label="Photographic services",
                    leaves=(
                        Leaf(
                            code="09.6.3.0",
                            label="Photographic services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.6.9",
                    label="Other cultural services",
                    leaves=(
                        Leaf(
                            code="09.6.9.0",
                            label="Other cultural services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.7",
            label="Newspapers, books and stationery",
            subgroups=(
                Subgroup(
                    code="09.7.1",
                    label="Books",
                    leaves=(
                        Leaf(
                            code="09.7.1.1",
                            label="Educational books and textbooks",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.7.1.9",
                            label="Other books",
                            excludes=(
                                ExcludeRef(code="09.2.1.2", label="stamp albums"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.7.2",
                    label="Newspapers and periodicals",
                    leaves=(
                        Leaf(
                            code="09.7.2.1",
                            label="Newspapers",
                            excludes=(),
                        ),
                        Leaf(
                            code="09.7.2.2",
                            label="Magazines and periodicals",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.7.3",
                    label="Miscellaneous printed matter",
                    leaves=(
                        Leaf(
                            code="09.7.3.0",
                            label="Miscellaneous printed matter",
                            excludes=(
                                ExcludeRef(
                                    code="07.4.1.1",
                                    label="pre-franked postcards, envelopes and aerogrammes",
                                ),
                                ExcludeRef(code="09.2.1.2", label="stamp albums"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="09.7.4",
                    label="Stationery and drawing materials",
                    leaves=(
                        Leaf(
                            code="09.7.4.0",
                            label="Stationery and drawing materials",
                            excludes=(
                                ExcludeRef(
                                    code="07.4.1.1",
                                    label="pre-franked postcards, envelopes and aerogrammes",
                                ),
                                ExcludeRef(code="08.1.3.2", label="pocket calculators"),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="09.8",
            label="Package holidays",
            subgroups=(
                Subgroup(
                    code="09.8.0",
                    label="Package holidays",
                    leaves=(
                        Leaf(
                            code="09.8.0.0",
                            label="Package holidays",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
