"""COICOP class 10 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="10",
    label="Education services",
    groups=(
        Group(
            code="10.1",
            label="Early childhood and primary education",
            subgroups=(
                Subgroup(
                    code="10.1.0",
                    label="Early childhood and primary education",
                    leaves=(
                        Leaf(
                            code="10.1.0.1",
                            label="Early childhood education",
                            excludes=(),
                        ),
                        Leaf(
                            code="10.1.0.2",
                            label="Primary education",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="10.2",
            label="Secondary education",
            subgroups=(
                Subgroup(
                    code="10.2.0",
                    label="Secondary education",
                    leaves=(
                        Leaf(
                            code="10.2.0.0",
                            label="Secondary education",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="10.3",
            label="Post-secondary non-tertiary education",
            subgroups=(
                Subgroup(
                    code="10.3.0",
                    label="Post-secondary non-tertiary education",
                    leaves=(
                        Leaf(
                            code="10.3.0.0",
                            label="Post-secondary non-tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="10.4",
            label="Tertiary education",
            subgroups=(
                Subgroup(
                    code="10.4.0",
                    label="Tertiary education",
                    leaves=(
                        Leaf(
                            code="10.4.0.0",
                            label="Tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="10.5",
            label="Education not defined by level",
            subgroups=(
                Subgroup(
                    code="10.5.0",
                    label="Education not defined by level",
                    leaves=(
                        Leaf(
                            code="10.5.0.1",
                            label="Tutoring",
                            excludes=(),
                        ),
                        Leaf(
                            code="10.5.0.9",
                            label="Other education not defined by level",
                            excludes=(
                                ExcludeRef(code="07.2.4.3", label="driving lessons"),
                                ExcludeRef(
                                    code="09.4.6",
                                    label="training courses for recreation and sports that are not part of an educational programme",
                                ),
                                ExcludeRef(
                                    code="09.7.1.1",
                                    label="removable media containing foreign language trainers",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
