"""COICOP class 11 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="11",
    label="Restaurants and accommodation services",
    groups=(
        Group(
            code="11.1",
            label="Food and beverage serving services",
            subgroups=(
                Subgroup(
                    code="11.1.1",
                    label="Restaurants, cafés and the like",
                    leaves=(
                        Leaf(
                            code="11.1.1.1",
                            label="Restaurants, cafés and the like – with full service",
                            excludes=(
                                ExcludeRef(code="02.3.0", label="tobacco purchases"),
                                ExcludeRef(
                                    code="07.3",
                                    label="food and beverage services on public transport, if not separately priced",
                                ),
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="food and beverage delivery, if separately priced",
                                ),
                                ExcludeRef(
                                    code="09.4.6.1",
                                    label="entrance fees for dancing establishments and nightclubs",
                                ),
                                ExcludeRef(
                                    code="09.8.0.0",
                                    label="food and beverage services provided in package holidays, if not separately priced",
                                ),
                                ExcludeRef(
                                    code="11.2",
                                    label="food and beverage services in hotels or other lodging establishments, if not separately priced from accommodation",
                                ),
                            ),
                        ),
                        Leaf(
                            code="11.1.1.2",
                            label="Restaurants, cafés and the like – with limited service",
                            excludes=(
                                ExcludeRef(code="02.3.0", label="tobacco purchases"),
                                ExcludeRef(
                                    code="07.3",
                                    label="food and beverage services on public transport, if not separately priced",
                                ),
                                ExcludeRef(
                                    code="07.4.9.2",
                                    label="food and beverage delivery, if separately priced",
                                ),
                                ExcludeRef(
                                    code="09.4.6.1",
                                    label="entrance fees for dancing establishments and nightclubs",
                                ),
                                ExcludeRef(
                                    code="09.8.0.0",
                                    label="food and beverage services provided in package holidays, if not separately priced",
                                ),
                                ExcludeRef(
                                    code="11.2",
                                    label="food and beverage services in hotels or other lodging establishments, if not separately priced from accommodation",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="11.1.2",
                    label="Canteens, cafeterias and refectories",
                    leaves=(
                        Leaf(
                            code="11.1.2.1",
                            label="Canteens and cafeterias of universities, schools and kindergartens",
                            excludes=(),
                        ),
                        Leaf(
                            code="11.1.2.9",
                            label="Other canteens, cafeterias and refectories",
                            excludes=(
                                ExcludeRef(
                                    code="06.3",
                                    label="food and beverages provided to hospital in-patients, if not separately priced",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="11.2",
            label="Accommodation services",
            subgroups=(
                Subgroup(
                    code="11.2.0",
                    label="Accommodation services",
                    leaves=(
                        Leaf(
                            code="11.2.0.1",
                            label="Hotels, motels, inns and similar accommodation services",
                            excludes=(
                                ExcludeRef(
                                    code="04.1.1.0",
                                    label="payments of households occupying a room in a hotel or boarding house as their main residence",
                                ),
                                ExcludeRef(
                                    code="04.1.2.1",
                                    label="rentals paid by households for a secondary residence or timeshare residence",
                                ),
                                ExcludeRef(code="08.3.1.0", label="telephone calls"),
                                ExcludeRef(code="09.8.0.0", label="package holidays"),
                                ExcludeRef(
                                    code="11.1.1",
                                    label="breakfast, meals and other food and beverages provided in accommodation and similar establishments, if separately priced",
                                ),
                            ),
                        ),
                        Leaf(
                            code="11.2.0.2",
                            label="Holiday centres, camping sites, youth hostels and similar accommodation services",
                            excludes=(
                                ExcludeRef(
                                    code="04.1.1.0",
                                    label="payments of households occupying a room in holiday centres, camping sites, youth hostels and similar accommodation as their main or secondary residence",
                                ),
                                ExcludeRef(code="08.3.1.0", label="telephone calls"),
                                ExcludeRef(
                                    code="11.1.1",
                                    label="breakfast, meals and other food and beverages provided in accommodation and similar establishments, if separately priced",
                                ),
                            ),
                        ),
                        Leaf(
                            code="11.2.0.3",
                            label="Accommodation services of boarding schools, universities and other educational establishments",
                            excludes=(
                                ExcludeRef(
                                    code="13.3.0.2",
                                    label="homes for disabled or maladjusted persons",
                                ),
                            ),
                        ),
                        Leaf(
                            code="11.2.0.9",
                            label="Other accommodation services",
                            excludes=(
                                ExcludeRef(code="08.3.1.0", label="telephone calls"),
                                ExcludeRef(
                                    code="11.1.1",
                                    label="breakfast, meals and other food and beverages provided in accommodation and similar establishments, if separately priced",
                                ),
                                ExcludeRef(
                                    code="13.3.0.2",
                                    label="homes for disabled or maladjusted persons",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
