"""COICOP class 12 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="12",
    label="Insurance and financial services",
    groups=(
        Group(
            code="12.1",
            label="Insurance",
            subgroups=(
                Subgroup(
                    code="12.1.1",
                    label="Life and accident insurance",
                    leaves=(
                        Leaf(
                            code="12.1.1.0",
                            label="Life and accident insurance",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.1.2",
                    label="Insurance connected with health",
                    leaves=(
                        Leaf(
                            code="12.1.2.0",
                            label="Insurance connected with health",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.1.3",
                    label="Insurance connected with dwellings",
                    leaves=(
                        Leaf(
                            code="12.1.3.0",
                            label="Insurance connected with dwellings",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.1.4",
                    label="Insurance connected with transport",
                    leaves=(
                        Leaf(
                            code="12.1.4.1",
                            label="Personal transport insurance",
                            excludes=(),
                        ),
                        Leaf(
                            code="12.1.4.2",
                            label="Travel insurance",
                            excludes=(
                                ExcludeRef(
                                    code="12.1.2.0", label="travel health insurance"
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.1.9",
                    label="Other insurance",
                    leaves=(
                        Leaf(
                            code="12.1.9.0",
                            label="Other insurance",
                            excludes=(
                                ExcludeRef(
                                    code="12.1.4.1",
                                    label="civil liability or damage to third parties or their property arising from the operation of personal transport equipment",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="12.2",
            label="Financial services",
            subgroups=(
                Subgroup(
                    code="12.2.1",
                    label="Financial intermediation services indirectly measured",
                    leaves=(
                        Leaf(
                            code="12.2.1.0",
                            label="Financial intermediation services indirectly measured",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.2.2",
                    label="Explicit charges by deposit-taking corporations",
                    leaves=(
                        Leaf(
                            code="12.2.2.0",
                            label="Explicit charges by deposit-taking corporations",
                            excludes=(
                                ExcludeRef(code="12.2.9.1", label="remittances fees"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="12.2.9",
                    label="Other financial services",
                    leaves=(
                        Leaf(
                            code="12.2.9.1",
                            label="Remittances fees",
                            excludes=(),
                        ),
                        Leaf(
                            code="12.2.9.9",
                            label="Other financial services n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
