"""COICOP class 13 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    ExcludeRef,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="13",
    label="Personal care, social protection and miscellaneous goods and services",
    groups=(
        Group(
            code="13.1",
            label="Personal care",
            subgroups=(
                Subgroup(
                    code="13.1.1",
                    label="Electric appliances for personal care",
                    leaves=(
                        Leaf(
                            code="13.1.1.1",
                            label="Purchase of electric appliances for personal care",
                            excludes=(
                                ExcludeRef(
                                    code="13.1.1.2",
                                    label="repair of electric appliances for personal care",
                                ),
                            ),
                        ),
                        Leaf(
                            code="13.1.1.2",
                            label="Repair of electric appliances for personal care",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="13.1.2",
                    label="Other appliances, articles and products for personal care",
                    leaves=(
                        Leaf(
                            code="13.1.2.0",
                            label="Other appliances, articles and products for personal care",
                            excludes=(
                                ExcludeRef(
                                    code="03.1.3.1",
                                    label="handkerchiefs made of fabric",
                                ),
                                ExcludeRef(code="06.1.2.1", label="baby scales"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="13.1.3",
                    label="Hairdressing salons and personal grooming establishments",
                    leaves=(
                        Leaf(
                            code="13.1.3.1",
                            label="Hairdressing",
                            excludes=(),
                        ),
                        Leaf(
                            code="13.1.3.2",
                            label="Personal grooming treatments",
                            excludes=(
                                ExcludeRef(code="09.4.5.0", label="animal tattooing"),
                                ExcludeRef(code="09.4.6.2", label="fitness centres"),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="13.2",
            label="Other personal effects",
            subgroups=(
                Subgroup(
                    code="13.2.1",
                    label="Jewellery and watches",
                    leaves=(
                        Leaf(
                            code="13.2.1.1",
                            label="Purchase of jewellery and watches",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.1.4",
                                    label="wall clocks, floor clocks, alarm clocks and travel clocks",
                                ),
                                ExcludeRef(code="08.1.4.0", label="radio clocks"),
                                ExcludeRef(code="08.1.9.1", label="smartwatches"),
                            ),
                        ),
                        Leaf(
                            code="13.2.1.2",
                            label="Repair and hire of jewellery, clocks and watches",
                            excludes=(
                                ExcludeRef(
                                    code="05.1.2.0",
                                    label="repair of floor standing and similar household clocks",
                                ),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="13.2.2",
                    label="Devotional articles and articles for religious and ritual celebrations",
                    leaves=(
                        Leaf(
                            code="13.2.2.0",
                            label="Devotional articles and articles for religious and ritual celebrations",
                            excludes=(
                                ExcludeRef(
                                    code="09.2.1.3",
                                    label="Christmas trees, holiday decorations (for Christmas, Easter, Hanukkah, Eid, Diwali and similar)",
                                ),
                                ExcludeRef(code="09.7.1.9", label="religious books"),
                                ExcludeRef(code="13.2.9.1", label="funerary articles"),
                            ),
                        ),
                    ),
                ),
                Subgroup(
                    code="13.2.9",
                    label="Other personal effects n.e.c.",
                    leaves=(
                        Leaf(
                            code="13.2.9.1",
                            label="Travel goods, baby articles and other personal effects n.e.c.",
                            excludes=(
                                ExcludeRef(code="05.1.1.1", label="baby furniture"),
                                ExcludeRef(code="05.2.1.9", label="shopping bags"),
                                ExcludeRef(code="05.4.0.3", label="feeding bottles"),
                                ExcludeRef(code="06.1.2.1", label="baby scales"),
                                ExcludeRef(
                                    code="07.2.1.3", label="car seats for babies"
                                ),
                                ExcludeRef(
                                    code="09.2.2.1",
                                    label="protection glasses for the practice of a sport",
                                ),
                                ExcludeRef(
                                    code="09.2.2.2",
                                    label="backpacks for camping and open-air recreation",
                                ),
                                ExcludeRef(
                                    code="09.2.2.2",
                                    label="umbrellas and parasols for the garden (05.1.1.2) or for the beach",
                                ),
                            ),
                        ),
                        Leaf(
                            code="13.2.9.2",
                            label="Repair and hire of other personal effects",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="13.3",
            label="Social protection",
            subgroups=(
                Subgroup(
                    code="13.3.0",
                    label="Social protection",
                    leaves=(
                        Leaf(
                            code="13.3.0.1",
                            label="Childcare services",
                            excludes=(
                                ExcludeRef(
                                    code="05.6.2.1", label="babysitters and so on"
                                ),
                                ExcludeRef(
                                    code="10.1.0.1", label="educational kindergartens"
                                ),
                            ),
                        ),
                        Leaf(
                            code="13.3.0.2",
                            label="Retirement homes for elderly persons and residences for disabled persons, not providing medical care",
                            excludes=(
                                ExcludeRef(
                                    code="06.3.2.0",
                                    label="services of mental health convalescent homes or hospitals",
                                ),
                            ),
                        ),
                        Leaf(
                            code="13.3.0.3",
                            label="Home care services for elderly and disabled",
                            excludes=(),
                        ),
                        Leaf(
                            code="13.3.0.9",
                            label="Other social protection services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="13.9",
            label="Other services",
            subgroups=(
                Subgroup(
                    code="13.9.0",
                    label="Other services",
                    leaves=(
                        Leaf(
                            code="13.9.0.1",
                            label="Prostitution",
                            excludes=(
                                ExcludeRef(
                                    code="11.1.1",
                                    label="food or beverages consumed in brothels, if separately priced",
                                ),
                            ),
                        ),
                        Leaf(
                            code="13.9.0.2",
                            label="Religious services",
                            excludes=(),
                        ),
                        Leaf(
                            code="13.9.0.9",
                            label="Other services n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
