"""COICOP class 14 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="14",
    label="Individual consumption expenditure of Non-profit Institutions Serving Households",
    groups=(
        Group(
            code="14.1",
            label="Housing",
            subgroups=(
                Subgroup(
                    code="14.1.0",
                    label="Housing",
                    leaves=(
                        Leaf(
                            code="14.1.0.0",
                            label="Housing",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="14.2",
            label="Health",
            subgroups=(
                Subgroup(
                    code="14.2.1",
                    label="Pharmaceutical products",
                    leaves=(
                        Leaf(
                            code="14.2.1.0",
                            label="Pharmaceutical products",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.2",
                    label="Other medical products",
                    leaves=(
                        Leaf(
                            code="14.2.2.0",
                            label="Other medical products",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.3",
                    label="Therapeutic appliances and equipment",
                    leaves=(
                        Leaf(
                            code="14.2.3.0",
                            label="Therapeutic appliances and equipment",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.4",
                    label="Outpatient medical services",
                    leaves=(
                        Leaf(
                            code="14.2.4.0",
                            label="Outpatient medical services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.5",
                    label="Outpatient dental services",
                    leaves=(
                        Leaf(
                            code="14.2.5.0",
                            label="Outpatient dental services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.6",
                    label="Outpatient paramedical services",
                    leaves=(
                        Leaf(
                            code="14.2.6.0",
                            label="Outpatient paramedical services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.7",
                    label="Hospital services",
                    leaves=(
                        Leaf(
                            code="14.2.7.0",
                            label="Hospital services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.2.8",
                    label="Other health services",
                    leaves=(
                        Leaf(
                            code="14.2.8.0",
                            label="Other health services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="14.3",
            label="Recreation and culture",
            subgroups=(
                Subgroup(
                    code="14.3.1",
                    label="Recreational and sporting services",
                    leaves=(
                        Leaf(
                            code="14.3.1.0",
                            label="Recreational and sporting services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.3.2",
                    label="Cultural services",
                    leaves=(
                        Leaf(
                            code="14.3.2.0",
                            label="Cultural services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="14.4",
            label="Education",
            subgroups=(
                Subgroup(
                    code="14.4.1",
                    label="Pre-primary and primary education",
                    leaves=(
                        Leaf(
                            code="14.4.1.0",
                            label="Pre-primary and primary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.4.2",
                    label="Secondary education",
                    leaves=(
                        Leaf(
                            code="14.4.2.0",
                            label="Secondary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.4.3",
                    label="Post-secondary non-tertiary education",
                    leaves=(
                        Leaf(
                            code="14.4.3.0",
                            label="Post-secondary non-tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.4.4",
                    label="Tertiary education",
                    leaves=(
                        Leaf(
                            code="14.4.4.0",
                            label="Tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.4.5",
                    label="Education not defined by level",
                    leaves=(
                        Leaf(
                            code="14.4.5.0",
                            label="Education not defined by level",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.4.6",
                    label="Other educational services",
                    leaves=(
                        Leaf(
                            code="14.4.6.0",
                            label="Other educational services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="14.5",
            label="Social protection",
            subgroups=(
                Subgroup(
                    code="14.5.0",
                    label="Social protection",
                    leaves=(
                        Leaf(
                            code="14.5.0.0",
                            label="Social protection",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="14.6",
            label="Other services",
            subgroups=(
                Subgroup(
                    code="14.6.1",
                    label="Religion",
                    leaves=(
                        Leaf(
                            code="14.6.1.0",
                            label="Religion",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.6.2",
                    label="Political parties, labour and professional organizations",
                    leaves=(
                        Leaf(
                            code="14.6.2.0",
                            label="Political parties, labour and professional organizations",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.6.3",
                    label="Environmental protection",
                    leaves=(
                        Leaf(
                            code="14.6.3.0",
                            label="Environmental protection",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="14.6.4",
                    label="Services n.e.c.",
                    leaves=(
                        Leaf(
                            code="14.6.4.0",
                            label="Services n.e.c.",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
