"""COICOP class 15 — auto-generated by tools/import_coicop_xlsx.py.

Do not edit by hand. To update, modify coicop_categories.xlsx and re-run the importer.
"""

from __future__ import annotations

from prices.enrich.keywords.types import (
    COICOPClass,
    Group,
    Leaf,
    Subgroup,
)


CLASS = COICOPClass(
    code="15",
    label="Individual consumption expenditure of general government",
    groups=(
        Group(
            code="15.1",
            label="Housing",
            subgroups=(
                Subgroup(
                    code="15.1.0",
                    label="Housing",
                    leaves=(
                        Leaf(
                            code="15.1.0.0",
                            label="Housing",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="15.2",
            label="Health",
            subgroups=(
                Subgroup(
                    code="15.2.1",
                    label="Pharmaceutical products",
                    leaves=(
                        Leaf(
                            code="15.2.1.0",
                            label="Pharmaceutical products",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.2",
                    label="Other medical products",
                    leaves=(
                        Leaf(
                            code="15.2.2.0",
                            label="Other medical products",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.3",
                    label="Therapeutic appliances and equipment",
                    leaves=(
                        Leaf(
                            code="15.2.3.0",
                            label="Therapeutic appliances and equipment",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.4",
                    label="Outpatient medical services",
                    leaves=(
                        Leaf(
                            code="15.2.4.0",
                            label="Outpatient medical services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.5",
                    label="Outpatient dental services",
                    leaves=(
                        Leaf(
                            code="15.2.5.0",
                            label="Outpatient dental services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.6",
                    label="Outpatient paramedical services",
                    leaves=(
                        Leaf(
                            code="15.2.6.0",
                            label="Outpatient paramedical services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.7",
                    label="Hospital services",
                    leaves=(
                        Leaf(
                            code="15.2.7.0",
                            label="Hospital services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.2.8",
                    label="Public health services",
                    leaves=(
                        Leaf(
                            code="15.2.8.0",
                            label="Public health services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="15.3",
            label="Recreation and culture",
            subgroups=(
                Subgroup(
                    code="15.3.1",
                    label="Recreational and sporting services",
                    leaves=(
                        Leaf(
                            code="15.3.1.0",
                            label="Recreational and sporting services",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.3.2",
                    label="Cultural services",
                    leaves=(
                        Leaf(
                            code="15.3.2.0",
                            label="Cultural services",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="15.4",
            label="Education",
            subgroups=(
                Subgroup(
                    code="15.4.1",
                    label="Pre-primary and primary education",
                    leaves=(
                        Leaf(
                            code="15.4.1.0",
                            label="Pre-primary and primary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.4.2",
                    label="Secondary education",
                    leaves=(
                        Leaf(
                            code="15.4.2.0",
                            label="Secondary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.4.3",
                    label="Post-secondary non-tertiary education",
                    leaves=(
                        Leaf(
                            code="15.4.3.0",
                            label="Post-secondary non-tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.4.4",
                    label="Tertiary education",
                    leaves=(
                        Leaf(
                            code="15.4.4.0",
                            label="Tertiary education",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.4.5",
                    label="Education not defined by level",
                    leaves=(
                        Leaf(
                            code="15.4.5.0",
                            label="Education not defined by level",
                            excludes=(),
                        ),
                    ),
                ),
                Subgroup(
                    code="15.4.6",
                    label="Subsidiary services to education",
                    leaves=(
                        Leaf(
                            code="15.4.6.0",
                            label="Subsidiary services to education",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
        Group(
            code="15.5",
            label="Social protection",
            subgroups=(
                Subgroup(
                    code="15.5.0",
                    label="Social protection",
                    leaves=(
                        Leaf(
                            code="15.5.0.0",
                            label="Social protection",
                            excludes=(),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
